# @package model

_target_: dau_build.build_steps.ResolvedConfigStep
spec_path: null
spec: ${oc.select:spec,null}
board: ${oc.select:board,null}
backend: ${oc.select:backend,null}
driver: ${oc.select:driver,null}
memory: ${oc.select:memory,null}
