# Changes here will be overwritten by Copier
_commit: 74b8054
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: dev@dau.dev
github: dau-dev
project_description: Build tools for dau
project_name: dau build
python_version_primary: '3.11'
team: the dau authors
