[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "dau-build"
description = "Build tools for dau projects"
version = "0.1.0"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
authors = [
    { name = "Tim Paine", email = "t.paine154@gmail.com" },
]
keywords = [
    "soc",
    "hardware",
    "fpga",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
]

dependencies = [
]

[project.optional-dependencies]
develop = [
    "check-manifest",
    "isort>=5,<6",
    "ruff>=0.3,<0.4",
    # test
    "pytest",
    "pytest-cov",
]
test = [
    "pytest",
    "pytest-cov",
]

[project.urls]
repository = "https://github.com/dau-dev/dau-build"
homepage = "https://github.com/dau-dev/dau-build"

[tool.isort]
combine_as_imports = true
include_trailing_comma = true
line_length = 150
profile = "black"

default_section = "THIRDPARTY"
sections = "FUTURE,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

known_first_party = "dau_build"

[tool.pytest.ini_options]
asyncio_mode = "strict"
testpaths = "dau_build/tests"

[tool.ruff]
line-length = 150

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
