`default_nettype none

// GENERATED by dau_build.scan_composition.generate_scan_composition_top_sv — do not
// edit. Scan composition sorted-scan: one scan fanned to 4
// lane(s) behind the DAU stream-job register contract with the NoC lane
// register block. Plain-Verilog top (BD module references require it).
module dau_mm_sorted_scan_job #(
    parameter [31:0] OPERATOR_BITMAP = 32'h00000000,
    parameter [31:0] LANE_COUNT = 32'd4,
    parameter [31:0] HOST_OPCODE_BITMAP = 32'h00000000,
    parameter [31:0] SORT_CAPACITY = 32'd16
) (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s_axi_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S_AXI:M_AXI, ASSOCIATED_RESET s_axi_aresetn" *)
    input wire s_axi_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s_axi_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input wire s_axi_aresetn,

    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S_AXI, PROTOCOL AXI4LITE, DATA_WIDTH 32, ADDR_WIDTH 16, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1" *)
    input wire [15:0] s_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWVALID" *)
    input wire s_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWREADY" *)
    output reg s_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WDATA" *)
    input wire [31:0] s_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WSTRB" *)
    input wire [3:0] s_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WVALID" *)
    input wire s_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WREADY" *)
    output reg s_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BRESP" *)
    output wire [1:0] s_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BVALID" *)
    output reg s_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BREADY" *)
    input wire s_axi_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARADDR" *)
    input wire [15:0] s_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARVALID" *)
    input wire s_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARREADY" *)
    output reg s_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RDATA" *)
    output reg [31:0] s_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RRESP" *)
    output wire [1:0] s_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RVALID" *)
    output reg s_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RREADY" *)
    input wire s_axi_rready,

    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M_AXI, PROTOCOL AXI4, DATA_WIDTH 64, ADDR_WIDTH 32, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, MAX_BURST_LENGTH 32, SUPPORTS_NARROW_BURST 0" *)
    output wire [31:0] m_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARLEN" *)
    output wire [7:0] m_axi_arlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARSIZE" *)
    output wire [2:0] m_axi_arsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARBURST" *)
    output wire [1:0] m_axi_arburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARVALID" *)
    output wire m_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARREADY" *)
    input wire m_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RDATA" *)
    input wire [63:0] m_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RRESP" *)
    input wire [1:0] m_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RLAST" *)
    input wire m_axi_rlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RVALID" *)
    input wire m_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RREADY" *)
    output wire m_axi_rready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWADDR" *)
    output wire [31:0] m_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWLEN" *)
    output wire [7:0] m_axi_awlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWSIZE" *)
    output wire [2:0] m_axi_awsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWBURST" *)
    output wire [1:0] m_axi_awburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWVALID" *)
    output wire m_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWREADY" *)
    input wire m_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WDATA" *)
    output wire [63:0] m_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WSTRB" *)
    output wire [7:0] m_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WLAST" *)
    output wire m_axi_wlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WVALID" *)
    output wire m_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WREADY" *)
    input wire m_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI BRESP" *)
    input wire [1:0] m_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI BVALID" *)
    input wire m_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI BREADY" *)
    output wire m_axi_bready
);
    // window-relative decode (the AXI address carries the BAR offset)
    localparam [11:0] ADDR_LAST_ERROR = 12'h02C;
    localparam [11:0] ADDR_JOB_CONTROL = 12'h050;
    localparam [11:0] ADDR_JOB_STATUS = 12'h054;
    localparam [11:0] ADDR_INPUT_ADDRESS_LOW = 12'h058;
    localparam [11:0] ADDR_INPUT_LENGTH_LOW = 12'h060;
    localparam [11:0] ADDR_LANE0_OUTPUT_ADDRESS = 12'h100;
    localparam [11:0] ADDR_LANE0_RESULT_LENGTH = 12'h104;
    localparam [11:0] ADDR_LANE0_RECORD_COUNT_LOW = 12'h108;
    localparam [11:0] ADDR_LANE0_RECORD_COUNT_HIGH = 12'h10C;
    localparam [11:0] ADDR_LANE0_ERROR = 12'h110;
    localparam [11:0] ADDR_LANE1_OUTPUT_ADDRESS = 12'h120;
    localparam [11:0] ADDR_LANE1_RESULT_LENGTH = 12'h124;
    localparam [11:0] ADDR_LANE1_RECORD_COUNT_LOW = 12'h128;
    localparam [11:0] ADDR_LANE1_RECORD_COUNT_HIGH = 12'h12C;
    localparam [11:0] ADDR_LANE1_ERROR = 12'h130;
    localparam [11:0] ADDR_LANE2_OUTPUT_ADDRESS = 12'h140;
    localparam [11:0] ADDR_LANE2_RESULT_LENGTH = 12'h144;
    localparam [11:0] ADDR_LANE2_RECORD_COUNT_LOW = 12'h148;
    localparam [11:0] ADDR_LANE2_RECORD_COUNT_HIGH = 12'h14C;
    localparam [11:0] ADDR_LANE2_ERROR = 12'h150;
    localparam [11:0] ADDR_LANE3_OUTPUT_ADDRESS = 12'h160;
    localparam [11:0] ADDR_LANE3_RESULT_LENGTH = 12'h164;
    localparam [11:0] ADDR_LANE3_RECORD_COUNT_LOW = 12'h168;
    localparam [11:0] ADDR_LANE3_RECORD_COUNT_HIGH = 12'h16C;
    localparam [11:0] ADDR_LANE3_ERROR = 12'h170;

    wire write_fire;
    wire read_fire;
    wire [15:0] selected_addr;
    wire [31:0] identity_rdata;
    wire [31:0] reset_request_unused;

    reg [31:0] input_address;
    reg [31:0] input_length_bytes;
    reg job_start;
    reg [31:0] lane_output_address_0;
    reg [31:0] lane_output_address_1;
    reg [31:0] lane_output_address_2;
    reg [31:0] lane_output_address_3;

    wire reader_busy;
    wire reader_done;
    wire reader_error;
    wire [7:0] reader_error_code;
    wire [63:0] dbg_first_stream_word;
    wire [31:0] dbg_first_araddr;
    wire [31:0] dbg_beats_while_idle;
    wire [31:0] dbg_final_fifo_count;
    wire scan_valid;
    wire scan_ready;
    wire [63:0] scan_data;
    wire scan_last;
    wire [3:0] part_out_valid;
    wire [3:0] part_out_ready;
    wire [255:0] part_out_data;
    wire [3:0] part_out_last;
    wire [3:0] part_status_valid;
    wire [3:0] part_status_ready;
    wire [3:0] part_status_error;
    wire [31:0] part_status_error_code;
    wire [1:0] wr_bresp;
    wire [127:0] wr_awaddr_flat;
    wire [31:0] wr_awlen_flat;
    wire [3:0] wr_awvalid_flat;
    wire [3:0] wr_awready_flat;
    wire [255:0] wr_wdata_flat;
    wire [3:0] wr_wlast_flat;
    wire [3:0] wr_wvalid_flat;
    wire [3:0] wr_wready_flat;
    wire [3:0] wr_bvalid_flat;
    wire [3:0] wr_bready_flat;
    wire filt_out_valid_0;
    wire filt_out_ready_0;
    wire [63:0] filt_out_data_0;
    wire filt_out_last_0;
    wire filt_status_valid_0;
    wire filt_status_ready_0;
    wire filt_status_error_0;
    wire [7:0] filt_status_error_code_0;
    wire tile_out_valid_0;
    wire tile_out_ready_0;
    wire [63:0] tile_out_data_0;
    wire tile_out_last_0;
    wire tile_status_valid_0;
    wire tile_status_ready_0;
    wire tile_status_error_0;
    wire [7:0] tile_status_error_code_0;
    wire [63:0] tile_bar_count_0;
    wire unit_status_valid_0;
    wire unit_status_ready_0;
    wire unit_status_error_0;
    wire [7:0] unit_status_error_code_0;
    wire writer_busy_0;
    wire writer_done_0;
    wire writer_error_0;
    wire [7:0] writer_error_code_0;
    wire [31:0] lane_result_length_0;
    wire [31:0] wr_awaddr_0;
    wire [7:0] wr_awlen_0;
    wire wr_awvalid_0;
    wire wr_awready_0;
    wire [63:0] wr_wdata_0;
    wire wr_wlast_0;
    wire wr_wvalid_0;
    wire wr_wready_0;
    wire wr_bvalid_0;
    wire wr_bready_0;
    reg [63:0] lane_bar_count_0;
    wire filt_out_valid_1;
    wire filt_out_ready_1;
    wire [63:0] filt_out_data_1;
    wire filt_out_last_1;
    wire filt_status_valid_1;
    wire filt_status_ready_1;
    wire filt_status_error_1;
    wire [7:0] filt_status_error_code_1;
    wire tile_out_valid_1;
    wire tile_out_ready_1;
    wire [63:0] tile_out_data_1;
    wire tile_out_last_1;
    wire tile_status_valid_1;
    wire tile_status_ready_1;
    wire tile_status_error_1;
    wire [7:0] tile_status_error_code_1;
    wire [63:0] tile_bar_count_1;
    wire unit_status_valid_1;
    wire unit_status_ready_1;
    wire unit_status_error_1;
    wire [7:0] unit_status_error_code_1;
    wire writer_busy_1;
    wire writer_done_1;
    wire writer_error_1;
    wire [7:0] writer_error_code_1;
    wire [31:0] lane_result_length_1;
    wire [31:0] wr_awaddr_1;
    wire [7:0] wr_awlen_1;
    wire wr_awvalid_1;
    wire wr_awready_1;
    wire [63:0] wr_wdata_1;
    wire wr_wlast_1;
    wire wr_wvalid_1;
    wire wr_wready_1;
    wire wr_bvalid_1;
    wire wr_bready_1;
    reg [63:0] lane_bar_count_1;
    wire filt_out_valid_2;
    wire filt_out_ready_2;
    wire [63:0] filt_out_data_2;
    wire filt_out_last_2;
    wire filt_status_valid_2;
    wire filt_status_ready_2;
    wire filt_status_error_2;
    wire [7:0] filt_status_error_code_2;
    wire tile_out_valid_2;
    wire tile_out_ready_2;
    wire [63:0] tile_out_data_2;
    wire tile_out_last_2;
    wire tile_status_valid_2;
    wire tile_status_ready_2;
    wire tile_status_error_2;
    wire [7:0] tile_status_error_code_2;
    wire [63:0] tile_bar_count_2;
    wire unit_status_valid_2;
    wire unit_status_ready_2;
    wire unit_status_error_2;
    wire [7:0] unit_status_error_code_2;
    wire writer_busy_2;
    wire writer_done_2;
    wire writer_error_2;
    wire [7:0] writer_error_code_2;
    wire [31:0] lane_result_length_2;
    wire [31:0] wr_awaddr_2;
    wire [7:0] wr_awlen_2;
    wire wr_awvalid_2;
    wire wr_awready_2;
    wire [63:0] wr_wdata_2;
    wire wr_wlast_2;
    wire wr_wvalid_2;
    wire wr_wready_2;
    wire wr_bvalid_2;
    wire wr_bready_2;
    reg [63:0] lane_bar_count_2;
    wire filt_out_valid_3;
    wire filt_out_ready_3;
    wire [63:0] filt_out_data_3;
    wire filt_out_last_3;
    wire filt_status_valid_3;
    wire filt_status_ready_3;
    wire filt_status_error_3;
    wire [7:0] filt_status_error_code_3;
    wire tile_out_valid_3;
    wire tile_out_ready_3;
    wire [63:0] tile_out_data_3;
    wire tile_out_last_3;
    wire tile_status_valid_3;
    wire tile_status_ready_3;
    wire tile_status_error_3;
    wire [7:0] tile_status_error_code_3;
    wire [63:0] tile_bar_count_3;
    wire unit_status_valid_3;
    wire unit_status_ready_3;
    wire unit_status_error_3;
    wire [7:0] unit_status_error_code_3;
    wire writer_busy_3;
    wire writer_done_3;
    wire writer_error_3;
    wire [7:0] writer_error_code_3;
    wire [31:0] lane_result_length_3;
    wire [31:0] wr_awaddr_3;
    wire [7:0] wr_awlen_3;
    wire wr_awvalid_3;
    wire wr_awready_3;
    wire [63:0] wr_wdata_3;
    wire wr_wlast_3;
    wire wr_wvalid_3;
    wire wr_wready_3;
    wire wr_bvalid_3;
    wire wr_bready_3;
    reg [63:0] lane_bar_count_3;

    // the 16-byte row grid is enforced before any unit starts: a rejected
    // length must not leave the writers waiting on a status
    reg length_fail;
    wire length_ok = (input_length_bytes != 32'd0) && (input_length_bytes[3:0] == 4'd0);
    wire unit_start = job_start && length_ok;

    wire job_busy = reader_busy || writer_busy_0 || writer_busy_1 || writer_busy_2 || writer_busy_3;
    wire job_done = length_fail || (reader_done && writer_done_0 && writer_done_1 && writer_done_2 && writer_done_3);
    reg job_error;
    reg [7:0] job_error_code;
    reg prev_done;
    reg pipeline_error_reset;
    wire lane_rst = !s_axi_aresetn || pipeline_error_reset;

    assign write_fire = !s_axi_bvalid && s_axi_awvalid && s_axi_wvalid;
    assign read_fire = !write_fire && !s_axi_rvalid && s_axi_arvalid;
    assign selected_addr = write_fire ? s_axi_awaddr : s_axi_araddr;
    assign s_axi_bresp = 2'b00;
    assign s_axi_rresp = 2'b00;

    always @(*) begin
        if (length_fail) begin
            job_error = 1'b1;
            job_error_code = 8'hFE;
        end else begin
            if (reader_error) begin
                job_error = 1'b1;
                job_error_code = reader_error_code;
            end else if (writer_error_0) begin
                job_error = 1'b1;
                job_error_code = writer_error_code_0;
            end else if (writer_error_1) begin
                job_error = 1'b1;
                job_error_code = writer_error_code_1;
            end else if (writer_error_2) begin
                job_error = 1'b1;
                job_error_code = writer_error_code_2;
            end else if (writer_error_3) begin
                job_error = 1'b1;
                job_error_code = writer_error_code_3;
            end else begin
                job_error = 1'b0;
                job_error_code = 8'd0;
            end
        end
    end

    dau_identity_registers #(
        .OPERATOR_BITMAP(OPERATOR_BITMAP),
        .LANE_COUNT(LANE_COUNT),
        .HOST_OPCODE_BITMAP(HOST_OPCODE_BITMAP),
        .SORT_CAPACITY(SORT_CAPACITY)
    ) identity_registers (
        .addr({4'h0, selected_addr[11:0]}),
        .wen(1'b0),
        .wdata(32'd0),
        .reset_request(reset_request_unused),
        .rdata(identity_rdata)
    );

    dau_axi_burst_reader #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32),
        .LENGTH_ALIGN_BITS(4)
    ) reader (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(unit_start),
        .read_address(input_address),
        .read_length_bytes(input_length_bytes),
        .busy(reader_busy),
        .done(reader_done),
        .error(reader_error),
        .error_code(reader_error_code),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rdata(m_axi_rdata),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),
        .stream_valid(scan_valid),
        .stream_ready(scan_ready),
        .stream_data(scan_data),
        .stream_last(scan_last),
        .dbg_first_stream_word(dbg_first_stream_word),
        .dbg_first_araddr(dbg_first_araddr),
        .dbg_beats_while_idle(dbg_beats_while_idle),
        .dbg_final_fifo_count(dbg_final_fifo_count)
    );

    dau_int32_range_partitioner #(
        .NUM_PARTITIONS(4)
    ) partitioner (
        .clk(s_axi_aclk),
        .rst(lane_rst),
        .cfg_splitters({32'h0000001E, 32'h00000014, 32'h0000000A}),
        .input_valid(scan_valid),
        .input_ready(scan_ready),
        .input_data(scan_data),
        .input_last(scan_last),
        .output_valid(part_out_valid),
        .output_ready(part_out_ready),
        .output_data(part_out_data),
        .output_last(part_out_last),
        .status_valid(part_status_valid),
        .status_ready(part_status_ready),
        .status_error(part_status_error),
        .status_error_code(part_status_error_code)
    );

    assign filt_out_valid_0 = part_out_valid[0];
    assign part_out_ready[0] = filt_out_ready_0;
    assign filt_out_data_0 = part_out_data[63:0];
    assign filt_out_last_0 = part_out_last[0];
    assign filt_status_valid_0 = part_status_valid[0];
    assign filt_status_error_0 = part_status_error[0];
    assign filt_status_error_code_0 = part_status_error_code[7:0];
    assign part_status_ready[0] = filt_status_ready_0;

    dau_int32_bitonic_sorter tile_0 (
        .clk(s_axi_aclk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_0),
        .input_ready(filt_out_ready_0),
        .input_data(filt_out_data_0),
        .input_last(filt_out_last_0),
        .output_valid(tile_out_valid_0),
        .output_ready(tile_out_ready_0),
        .output_data(tile_out_data_0),
        .output_last(tile_out_last_0),
        .status_valid(tile_status_valid_0),
        .status_ready(tile_status_ready_0),
        .status_error(tile_status_error_0),
        .status_error_code(tile_status_error_code_0),
        .sorted_count(tile_bar_count_0)
    );

    assign unit_status_valid_0 = tile_status_valid_0 || filt_status_valid_0;
    assign unit_status_error_0 = filt_status_valid_0 ? filt_status_error_0 : tile_status_error_0;
    assign unit_status_error_code_0 = filt_status_valid_0 ? filt_status_error_code_0 : tile_status_error_code_0;
    assign filt_status_ready_0 = unit_status_ready_0 && filt_status_valid_0;
    assign tile_status_ready_0 = unit_status_ready_0 && !filt_status_valid_0;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_0 (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(unit_start),
        .output_address(lane_output_address_0),
        .busy(writer_busy_0),
        .done(writer_done_0),
        .error(writer_error_0),
        .error_code(writer_error_code_0),
        .result_length_bytes(lane_result_length_0),
        .m_axi_awaddr(wr_awaddr_0),
        .m_axi_awlen(wr_awlen_0),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_0),
        .m_axi_awready(wr_awready_0),
        .m_axi_wdata(wr_wdata_0),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_0),
        .m_axi_wvalid(wr_wvalid_0),
        .m_axi_wready(wr_wready_0),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_0),
        .m_axi_bready(wr_bready_0),
        .record_valid(tile_out_valid_0),
        .record_ready(tile_out_ready_0),
        .record_data(tile_out_data_0),
        .record_last(tile_out_last_0),
        .status_valid(unit_status_valid_0),
        .status_ready(unit_status_ready_0),
        .status_error(unit_status_error_0),
        .status_error_code(unit_status_error_code_0)
    );

    assign filt_out_valid_1 = part_out_valid[1];
    assign part_out_ready[1] = filt_out_ready_1;
    assign filt_out_data_1 = part_out_data[127:64];
    assign filt_out_last_1 = part_out_last[1];
    assign filt_status_valid_1 = part_status_valid[1];
    assign filt_status_error_1 = part_status_error[1];
    assign filt_status_error_code_1 = part_status_error_code[15:8];
    assign part_status_ready[1] = filt_status_ready_1;

    dau_int32_bitonic_sorter tile_1 (
        .clk(s_axi_aclk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_1),
        .input_ready(filt_out_ready_1),
        .input_data(filt_out_data_1),
        .input_last(filt_out_last_1),
        .output_valid(tile_out_valid_1),
        .output_ready(tile_out_ready_1),
        .output_data(tile_out_data_1),
        .output_last(tile_out_last_1),
        .status_valid(tile_status_valid_1),
        .status_ready(tile_status_ready_1),
        .status_error(tile_status_error_1),
        .status_error_code(tile_status_error_code_1),
        .sorted_count(tile_bar_count_1)
    );

    assign unit_status_valid_1 = tile_status_valid_1 || filt_status_valid_1;
    assign unit_status_error_1 = filt_status_valid_1 ? filt_status_error_1 : tile_status_error_1;
    assign unit_status_error_code_1 = filt_status_valid_1 ? filt_status_error_code_1 : tile_status_error_code_1;
    assign filt_status_ready_1 = unit_status_ready_1 && filt_status_valid_1;
    assign tile_status_ready_1 = unit_status_ready_1 && !filt_status_valid_1;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_1 (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(unit_start),
        .output_address(lane_output_address_1),
        .busy(writer_busy_1),
        .done(writer_done_1),
        .error(writer_error_1),
        .error_code(writer_error_code_1),
        .result_length_bytes(lane_result_length_1),
        .m_axi_awaddr(wr_awaddr_1),
        .m_axi_awlen(wr_awlen_1),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_1),
        .m_axi_awready(wr_awready_1),
        .m_axi_wdata(wr_wdata_1),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_1),
        .m_axi_wvalid(wr_wvalid_1),
        .m_axi_wready(wr_wready_1),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_1),
        .m_axi_bready(wr_bready_1),
        .record_valid(tile_out_valid_1),
        .record_ready(tile_out_ready_1),
        .record_data(tile_out_data_1),
        .record_last(tile_out_last_1),
        .status_valid(unit_status_valid_1),
        .status_ready(unit_status_ready_1),
        .status_error(unit_status_error_1),
        .status_error_code(unit_status_error_code_1)
    );

    assign filt_out_valid_2 = part_out_valid[2];
    assign part_out_ready[2] = filt_out_ready_2;
    assign filt_out_data_2 = part_out_data[191:128];
    assign filt_out_last_2 = part_out_last[2];
    assign filt_status_valid_2 = part_status_valid[2];
    assign filt_status_error_2 = part_status_error[2];
    assign filt_status_error_code_2 = part_status_error_code[23:16];
    assign part_status_ready[2] = filt_status_ready_2;

    dau_int32_bitonic_sorter tile_2 (
        .clk(s_axi_aclk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_2),
        .input_ready(filt_out_ready_2),
        .input_data(filt_out_data_2),
        .input_last(filt_out_last_2),
        .output_valid(tile_out_valid_2),
        .output_ready(tile_out_ready_2),
        .output_data(tile_out_data_2),
        .output_last(tile_out_last_2),
        .status_valid(tile_status_valid_2),
        .status_ready(tile_status_ready_2),
        .status_error(tile_status_error_2),
        .status_error_code(tile_status_error_code_2),
        .sorted_count(tile_bar_count_2)
    );

    assign unit_status_valid_2 = tile_status_valid_2 || filt_status_valid_2;
    assign unit_status_error_2 = filt_status_valid_2 ? filt_status_error_2 : tile_status_error_2;
    assign unit_status_error_code_2 = filt_status_valid_2 ? filt_status_error_code_2 : tile_status_error_code_2;
    assign filt_status_ready_2 = unit_status_ready_2 && filt_status_valid_2;
    assign tile_status_ready_2 = unit_status_ready_2 && !filt_status_valid_2;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_2 (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(unit_start),
        .output_address(lane_output_address_2),
        .busy(writer_busy_2),
        .done(writer_done_2),
        .error(writer_error_2),
        .error_code(writer_error_code_2),
        .result_length_bytes(lane_result_length_2),
        .m_axi_awaddr(wr_awaddr_2),
        .m_axi_awlen(wr_awlen_2),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_2),
        .m_axi_awready(wr_awready_2),
        .m_axi_wdata(wr_wdata_2),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_2),
        .m_axi_wvalid(wr_wvalid_2),
        .m_axi_wready(wr_wready_2),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_2),
        .m_axi_bready(wr_bready_2),
        .record_valid(tile_out_valid_2),
        .record_ready(tile_out_ready_2),
        .record_data(tile_out_data_2),
        .record_last(tile_out_last_2),
        .status_valid(unit_status_valid_2),
        .status_ready(unit_status_ready_2),
        .status_error(unit_status_error_2),
        .status_error_code(unit_status_error_code_2)
    );

    assign filt_out_valid_3 = part_out_valid[3];
    assign part_out_ready[3] = filt_out_ready_3;
    assign filt_out_data_3 = part_out_data[255:192];
    assign filt_out_last_3 = part_out_last[3];
    assign filt_status_valid_3 = part_status_valid[3];
    assign filt_status_error_3 = part_status_error[3];
    assign filt_status_error_code_3 = part_status_error_code[31:24];
    assign part_status_ready[3] = filt_status_ready_3;

    dau_int32_bitonic_sorter tile_3 (
        .clk(s_axi_aclk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_3),
        .input_ready(filt_out_ready_3),
        .input_data(filt_out_data_3),
        .input_last(filt_out_last_3),
        .output_valid(tile_out_valid_3),
        .output_ready(tile_out_ready_3),
        .output_data(tile_out_data_3),
        .output_last(tile_out_last_3),
        .status_valid(tile_status_valid_3),
        .status_ready(tile_status_ready_3),
        .status_error(tile_status_error_3),
        .status_error_code(tile_status_error_code_3),
        .sorted_count(tile_bar_count_3)
    );

    assign unit_status_valid_3 = tile_status_valid_3 || filt_status_valid_3;
    assign unit_status_error_3 = filt_status_valid_3 ? filt_status_error_3 : tile_status_error_3;
    assign unit_status_error_code_3 = filt_status_valid_3 ? filt_status_error_code_3 : tile_status_error_code_3;
    assign filt_status_ready_3 = unit_status_ready_3 && filt_status_valid_3;
    assign tile_status_ready_3 = unit_status_ready_3 && !filt_status_valid_3;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_3 (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(unit_start),
        .output_address(lane_output_address_3),
        .busy(writer_busy_3),
        .done(writer_done_3),
        .error(writer_error_3),
        .error_code(writer_error_code_3),
        .result_length_bytes(lane_result_length_3),
        .m_axi_awaddr(wr_awaddr_3),
        .m_axi_awlen(wr_awlen_3),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_3),
        .m_axi_awready(wr_awready_3),
        .m_axi_wdata(wr_wdata_3),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_3),
        .m_axi_wvalid(wr_wvalid_3),
        .m_axi_wready(wr_wready_3),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_3),
        .m_axi_bready(wr_bready_3),
        .record_valid(tile_out_valid_3),
        .record_ready(tile_out_ready_3),
        .record_data(tile_out_data_3),
        .record_last(tile_out_last_3),
        .status_valid(unit_status_valid_3),
        .status_ready(unit_status_ready_3),
        .status_error(unit_status_error_3),
        .status_error_code(unit_status_error_code_3)
    );

    assign wr_awaddr_flat[31:0] = wr_awaddr_0;
    assign wr_awlen_flat[7:0] = wr_awlen_0;
    assign wr_awvalid_flat[0] = wr_awvalid_0;
    assign wr_awready_0 = wr_awready_flat[0];
    assign wr_wdata_flat[63:0] = wr_wdata_0;
    assign wr_wlast_flat[0] = wr_wlast_0;
    assign wr_wvalid_flat[0] = wr_wvalid_0;
    assign wr_wready_0 = wr_wready_flat[0];
    assign wr_bvalid_0 = wr_bvalid_flat[0];
    assign wr_bready_flat[0] = wr_bready_0;
    assign wr_awaddr_flat[63:32] = wr_awaddr_1;
    assign wr_awlen_flat[15:8] = wr_awlen_1;
    assign wr_awvalid_flat[1] = wr_awvalid_1;
    assign wr_awready_1 = wr_awready_flat[1];
    assign wr_wdata_flat[127:64] = wr_wdata_1;
    assign wr_wlast_flat[1] = wr_wlast_1;
    assign wr_wvalid_flat[1] = wr_wvalid_1;
    assign wr_wready_1 = wr_wready_flat[1];
    assign wr_bvalid_1 = wr_bvalid_flat[1];
    assign wr_bready_flat[1] = wr_bready_1;
    assign wr_awaddr_flat[95:64] = wr_awaddr_2;
    assign wr_awlen_flat[23:16] = wr_awlen_2;
    assign wr_awvalid_flat[2] = wr_awvalid_2;
    assign wr_awready_2 = wr_awready_flat[2];
    assign wr_wdata_flat[191:128] = wr_wdata_2;
    assign wr_wlast_flat[2] = wr_wlast_2;
    assign wr_wvalid_flat[2] = wr_wvalid_2;
    assign wr_wready_2 = wr_wready_flat[2];
    assign wr_bvalid_2 = wr_bvalid_flat[2];
    assign wr_bready_flat[2] = wr_bready_2;
    assign wr_awaddr_flat[127:96] = wr_awaddr_3;
    assign wr_awlen_flat[31:24] = wr_awlen_3;
    assign wr_awvalid_flat[3] = wr_awvalid_3;
    assign wr_awready_3 = wr_awready_flat[3];
    assign wr_wdata_flat[255:192] = wr_wdata_3;
    assign wr_wlast_flat[3] = wr_wlast_3;
    assign wr_wvalid_flat[3] = wr_wvalid_3;
    assign wr_wready_3 = wr_wready_flat[3];
    assign wr_bvalid_3 = wr_bvalid_flat[3];
    assign wr_bready_flat[3] = wr_bready_3;

    dau_axi_write_mux #(
        .NUM_INPUTS(4),
        .ADDR_WIDTH(32)
    ) write_mux (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .s_awaddr(wr_awaddr_flat),
        .s_awlen(wr_awlen_flat),
        .s_awvalid(wr_awvalid_flat),
        .s_awready(wr_awready_flat),
        .s_wdata(wr_wdata_flat),
        .s_wlast(wr_wlast_flat),
        .s_wvalid(wr_wvalid_flat),
        .s_wready(wr_wready_flat),
        .s_bresp(wr_bresp),
        .s_bvalid(wr_bvalid_flat),
        .s_bready(wr_bready_flat),
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready)
    );

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_awready <= 1'b0;
            s_axi_wready <= 1'b0;
            s_axi_bvalid <= 1'b0;
            s_axi_arready <= 1'b0;
            s_axi_rdata <= 32'h0000_0000;
            s_axi_rvalid <= 1'b0;
            input_address <= 32'd0;
            input_length_bytes <= 32'd0;
            job_start <= 1'b0;
            length_fail <= 1'b0;
            prev_done <= 1'b1;
            pipeline_error_reset <= 1'b0;
            lane_output_address_0 <= 32'd0;
            lane_output_address_1 <= 32'd0;
            lane_output_address_2 <= 32'd0;
            lane_output_address_3 <= 32'd0;
            lane_bar_count_0 <= 64'd0;
            lane_bar_count_1 <= 64'd0;
            lane_bar_count_2 <= 64'd0;
            lane_bar_count_3 <= 64'd0;
        end else begin
            job_start <= 1'b0;
            prev_done <= job_done;
            pipeline_error_reset <= job_done && !prev_done && job_error;
            if (job_start) begin
                length_fail <= !length_ok;
                lane_bar_count_0 <= 64'd0;
                lane_bar_count_1 <= 64'd0;
                lane_bar_count_2 <= 64'd0;
                lane_bar_count_3 <= 64'd0;
            end
            if (tile_status_valid_0 && tile_status_ready_0) begin
                lane_bar_count_0 <= tile_bar_count_0;
            end
            if (tile_status_valid_1 && tile_status_ready_1) begin
                lane_bar_count_1 <= tile_bar_count_1;
            end
            if (tile_status_valid_2 && tile_status_ready_2) begin
                lane_bar_count_2 <= tile_bar_count_2;
            end
            if (tile_status_valid_3 && tile_status_ready_3) begin
                lane_bar_count_3 <= tile_bar_count_3;
            end
            s_axi_awready <= write_fire;
            s_axi_wready <= write_fire;
            s_axi_arready <= read_fire;

            if (write_fire) begin
                s_axi_bvalid <= 1'b1;
                case (s_axi_awaddr[11:0])
                    ADDR_JOB_CONTROL: job_start <= s_axi_wdata[0];
                    ADDR_INPUT_ADDRESS_LOW: input_address <= s_axi_wdata[31:0];
                    ADDR_INPUT_LENGTH_LOW: input_length_bytes <= s_axi_wdata;
                    ADDR_LANE0_OUTPUT_ADDRESS: lane_output_address_0 <= s_axi_wdata;
                    ADDR_LANE1_OUTPUT_ADDRESS: lane_output_address_1 <= s_axi_wdata;
                    ADDR_LANE2_OUTPUT_ADDRESS: lane_output_address_2 <= s_axi_wdata;
                    ADDR_LANE3_OUTPUT_ADDRESS: lane_output_address_3 <= s_axi_wdata;
                    default: ;  // other job fields accepted and ignored
                endcase
            end else if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid <= 1'b0;
            end

            if (read_fire) begin
                case (s_axi_araddr[11:0])
                    ADDR_JOB_CONTROL: s_axi_rdata <= 32'd0;
                    ADDR_JOB_STATUS: s_axi_rdata <= {28'd0, job_error, job_done, job_busy, !job_busy};
                    ADDR_LAST_ERROR: s_axi_rdata <= {24'd0, job_error_code};
                    ADDR_INPUT_ADDRESS_LOW: s_axi_rdata <= input_address[31:0];
                    ADDR_INPUT_LENGTH_LOW: s_axi_rdata <= input_length_bytes;
                    12'hFC0: s_axi_rdata <= dbg_first_stream_word[31:0];
                    12'hFC4: s_axi_rdata <= dbg_first_stream_word[63:32];
                    12'hFC8: s_axi_rdata <= dbg_first_araddr;
                    12'hFCC: s_axi_rdata <= dbg_beats_while_idle;
                    12'hFD0: s_axi_rdata <= dbg_final_fifo_count;
                    ADDR_LANE0_OUTPUT_ADDRESS: s_axi_rdata <= lane_output_address_0[31:0];
                    ADDR_LANE0_RESULT_LENGTH: s_axi_rdata <= lane_result_length_0;
                    ADDR_LANE0_RECORD_COUNT_LOW: s_axi_rdata <= lane_bar_count_0[31:0];
                    ADDR_LANE0_RECORD_COUNT_HIGH: s_axi_rdata <= lane_bar_count_0[63:32];
                    ADDR_LANE0_ERROR: s_axi_rdata <= {24'd0, writer_error_code_0};
                    ADDR_LANE1_OUTPUT_ADDRESS: s_axi_rdata <= lane_output_address_1[31:0];
                    ADDR_LANE1_RESULT_LENGTH: s_axi_rdata <= lane_result_length_1;
                    ADDR_LANE1_RECORD_COUNT_LOW: s_axi_rdata <= lane_bar_count_1[31:0];
                    ADDR_LANE1_RECORD_COUNT_HIGH: s_axi_rdata <= lane_bar_count_1[63:32];
                    ADDR_LANE1_ERROR: s_axi_rdata <= {24'd0, writer_error_code_1};
                    ADDR_LANE2_OUTPUT_ADDRESS: s_axi_rdata <= lane_output_address_2[31:0];
                    ADDR_LANE2_RESULT_LENGTH: s_axi_rdata <= lane_result_length_2;
                    ADDR_LANE2_RECORD_COUNT_LOW: s_axi_rdata <= lane_bar_count_2[31:0];
                    ADDR_LANE2_RECORD_COUNT_HIGH: s_axi_rdata <= lane_bar_count_2[63:32];
                    ADDR_LANE2_ERROR: s_axi_rdata <= {24'd0, writer_error_code_2};
                    ADDR_LANE3_OUTPUT_ADDRESS: s_axi_rdata <= lane_output_address_3[31:0];
                    ADDR_LANE3_RESULT_LENGTH: s_axi_rdata <= lane_result_length_3;
                    ADDR_LANE3_RECORD_COUNT_LOW: s_axi_rdata <= lane_bar_count_3[31:0];
                    ADDR_LANE3_RECORD_COUNT_HIGH: s_axi_rdata <= lane_bar_count_3[63:32];
                    ADDR_LANE3_ERROR: s_axi_rdata <= {24'd0, writer_error_code_3};
                    default: s_axi_rdata <= identity_rdata;
                endcase
                s_axi_rvalid <= 1'b1;
            end else if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid <= 1'b0;
            end
        end
    end
endmodule

`default_nettype wire
