`default_nettype none

// GENERATED by dau_build.scan_composition.generate_scan_composition_sim_sv — do not
// edit. Scan-composition sim harness sorted-scan: the pipeline the
// shell top wires — one scan fanned to 4 lane(s) through the shared
// write mux — behind the job-level control surface and closed by the
// backdoor AXI RAM standing in for the platform memory.
module dau_mm_sorted_scan_job_sim (
    input wire clk,
    input wire rst,

    input wire start,
    input wire [31:0] input_address,
    input wire [31:0] input_length_bytes,
    input wire [95:0] cfg_splitters,
    input wire [127:0] lane_output_address,
    output wire busy,
    output wire done,
    output reg error,
    output reg [7:0] error_code,
    output wire [127:0] lane_result_length_bytes,
    output wire [255:0] lane_count,

    input wire bd_write,
    input wire [31:0] bd_index,
    input wire [63:0] bd_wdata,
    output wire [63:0] bd_rdata
);
    wire reader_busy;
    wire reader_done;
    wire reader_error;
    wire [7:0] reader_error_code;
    wire [31:0] rd_araddr;
    wire [7:0] rd_arlen;
    wire [2:0] rd_arsize;
    wire [1:0] rd_arburst;
    wire rd_arvalid;
    wire rd_arready;
    wire [63:0] rd_rdata;
    wire [1:0] rd_rresp;
    wire rd_rlast;
    wire rd_rvalid;
    wire rd_rready;
    wire scan_valid;
    wire scan_ready;
    wire [63:0] scan_data;
    wire scan_last;
    wire [3:0] part_out_valid;
    wire [3:0] part_out_ready;
    wire [255:0] part_out_data;
    wire [3:0] part_out_last;
    wire [3:0] part_status_valid;
    wire [3:0] part_status_ready;
    wire [3:0] part_status_error;
    wire [31:0] part_status_error_code;
    wire [1:0] wr_bresp;
    wire [127:0] wr_awaddr_flat;
    wire [31:0] wr_awlen_flat;
    wire [3:0] wr_awvalid_flat;
    wire [3:0] wr_awready_flat;
    wire [255:0] wr_wdata_flat;
    wire [3:0] wr_wlast_flat;
    wire [3:0] wr_wvalid_flat;
    wire [3:0] wr_wready_flat;
    wire [3:0] wr_bvalid_flat;
    wire [3:0] wr_bready_flat;
    wire [31:0] mx_awaddr;
    wire [7:0] mx_awlen;
    wire [2:0] mx_awsize;
    wire [1:0] mx_awburst;
    wire mx_awvalid;
    wire mx_awready;
    wire [63:0] mx_wdata;
    wire [7:0] mx_wstrb;
    wire mx_wlast;
    wire mx_wvalid;
    wire mx_wready;
    wire [1:0] mx_bresp;
    wire mx_bvalid;
    wire mx_bready;
    wire filt_out_valid_0;
    wire filt_out_ready_0;
    wire [63:0] filt_out_data_0;
    wire filt_out_last_0;
    wire filt_status_valid_0;
    wire filt_status_ready_0;
    wire filt_status_error_0;
    wire [7:0] filt_status_error_code_0;
    wire tile_out_valid_0;
    wire tile_out_ready_0;
    wire [63:0] tile_out_data_0;
    wire tile_out_last_0;
    wire tile_status_valid_0;
    wire tile_status_ready_0;
    wire tile_status_error_0;
    wire [7:0] tile_status_error_code_0;
    wire [63:0] tile_bar_count_0;
    wire unit_status_valid_0;
    wire unit_status_ready_0;
    wire unit_status_error_0;
    wire [7:0] unit_status_error_code_0;
    wire writer_busy_0;
    wire writer_done_0;
    wire writer_error_0;
    wire [7:0] writer_error_code_0;
    wire [31:0] lane_result_length_0;
    wire [31:0] wr_awaddr_0;
    wire [7:0] wr_awlen_0;
    wire wr_awvalid_0;
    wire wr_awready_0;
    wire [63:0] wr_wdata_0;
    wire wr_wlast_0;
    wire wr_wvalid_0;
    wire wr_wready_0;
    wire wr_bvalid_0;
    wire wr_bready_0;
    reg [63:0] lane_bar_count_0;
    wire filt_out_valid_1;
    wire filt_out_ready_1;
    wire [63:0] filt_out_data_1;
    wire filt_out_last_1;
    wire filt_status_valid_1;
    wire filt_status_ready_1;
    wire filt_status_error_1;
    wire [7:0] filt_status_error_code_1;
    wire tile_out_valid_1;
    wire tile_out_ready_1;
    wire [63:0] tile_out_data_1;
    wire tile_out_last_1;
    wire tile_status_valid_1;
    wire tile_status_ready_1;
    wire tile_status_error_1;
    wire [7:0] tile_status_error_code_1;
    wire [63:0] tile_bar_count_1;
    wire unit_status_valid_1;
    wire unit_status_ready_1;
    wire unit_status_error_1;
    wire [7:0] unit_status_error_code_1;
    wire writer_busy_1;
    wire writer_done_1;
    wire writer_error_1;
    wire [7:0] writer_error_code_1;
    wire [31:0] lane_result_length_1;
    wire [31:0] wr_awaddr_1;
    wire [7:0] wr_awlen_1;
    wire wr_awvalid_1;
    wire wr_awready_1;
    wire [63:0] wr_wdata_1;
    wire wr_wlast_1;
    wire wr_wvalid_1;
    wire wr_wready_1;
    wire wr_bvalid_1;
    wire wr_bready_1;
    reg [63:0] lane_bar_count_1;
    wire filt_out_valid_2;
    wire filt_out_ready_2;
    wire [63:0] filt_out_data_2;
    wire filt_out_last_2;
    wire filt_status_valid_2;
    wire filt_status_ready_2;
    wire filt_status_error_2;
    wire [7:0] filt_status_error_code_2;
    wire tile_out_valid_2;
    wire tile_out_ready_2;
    wire [63:0] tile_out_data_2;
    wire tile_out_last_2;
    wire tile_status_valid_2;
    wire tile_status_ready_2;
    wire tile_status_error_2;
    wire [7:0] tile_status_error_code_2;
    wire [63:0] tile_bar_count_2;
    wire unit_status_valid_2;
    wire unit_status_ready_2;
    wire unit_status_error_2;
    wire [7:0] unit_status_error_code_2;
    wire writer_busy_2;
    wire writer_done_2;
    wire writer_error_2;
    wire [7:0] writer_error_code_2;
    wire [31:0] lane_result_length_2;
    wire [31:0] wr_awaddr_2;
    wire [7:0] wr_awlen_2;
    wire wr_awvalid_2;
    wire wr_awready_2;
    wire [63:0] wr_wdata_2;
    wire wr_wlast_2;
    wire wr_wvalid_2;
    wire wr_wready_2;
    wire wr_bvalid_2;
    wire wr_bready_2;
    reg [63:0] lane_bar_count_2;
    wire filt_out_valid_3;
    wire filt_out_ready_3;
    wire [63:0] filt_out_data_3;
    wire filt_out_last_3;
    wire filt_status_valid_3;
    wire filt_status_ready_3;
    wire filt_status_error_3;
    wire [7:0] filt_status_error_code_3;
    wire tile_out_valid_3;
    wire tile_out_ready_3;
    wire [63:0] tile_out_data_3;
    wire tile_out_last_3;
    wire tile_status_valid_3;
    wire tile_status_ready_3;
    wire tile_status_error_3;
    wire [7:0] tile_status_error_code_3;
    wire [63:0] tile_bar_count_3;
    wire unit_status_valid_3;
    wire unit_status_ready_3;
    wire unit_status_error_3;
    wire [7:0] unit_status_error_code_3;
    wire writer_busy_3;
    wire writer_done_3;
    wire writer_error_3;
    wire [7:0] writer_error_code_3;
    wire [31:0] lane_result_length_3;
    wire [31:0] wr_awaddr_3;
    wire [7:0] wr_awlen_3;
    wire wr_awvalid_3;
    wire wr_awready_3;
    wire [63:0] wr_wdata_3;
    wire wr_wlast_3;
    wire wr_wvalid_3;
    wire wr_wready_3;
    wire wr_bvalid_3;
    wire wr_bready_3;
    reg [63:0] lane_bar_count_3;

    wire [31:0] lane_output_address_0 = lane_output_address[31:0];
    assign lane_result_length_bytes[31:0] = lane_result_length_0;
    assign lane_count[63:0] = lane_bar_count_0;
    wire [31:0] lane_output_address_1 = lane_output_address[63:32];
    assign lane_result_length_bytes[63:32] = lane_result_length_1;
    assign lane_count[127:64] = lane_bar_count_1;
    wire [31:0] lane_output_address_2 = lane_output_address[95:64];
    assign lane_result_length_bytes[95:64] = lane_result_length_2;
    assign lane_count[191:128] = lane_bar_count_2;
    wire [31:0] lane_output_address_3 = lane_output_address[127:96];
    assign lane_result_length_bytes[127:96] = lane_result_length_3;
    assign lane_count[255:192] = lane_bar_count_3;

    // recover mid-stream lanes after an error before the next job
    reg prev_done;
    reg pipeline_error_reset;
    wire lane_rst = rst || pipeline_error_reset;

    // the 16-byte row grid is enforced before any unit starts: a rejected
    // length must not leave the writers waiting on a status
    reg length_fail;
    wire length_ok = (input_length_bytes != 32'd0) && (input_length_bytes[3:0] == 4'd0);
    wire unit_start = start && length_ok;

    assign busy = reader_busy || writer_busy_0 || writer_busy_1 || writer_busy_2 || writer_busy_3;
    assign done = length_fail || (reader_done && writer_done_0 && writer_done_1 && writer_done_2 && writer_done_3);

    always @(*) begin
        if (length_fail) begin
            error = 1'b1;
            error_code = 8'hFE;
        end else begin
            if (reader_error) begin
                error = 1'b1;
                error_code = reader_error_code;
            end else if (writer_error_0) begin
                error = 1'b1;
                error_code = writer_error_code_0;
            end else if (writer_error_1) begin
                error = 1'b1;
                error_code = writer_error_code_1;
            end else if (writer_error_2) begin
                error = 1'b1;
                error_code = writer_error_code_2;
            end else if (writer_error_3) begin
                error = 1'b1;
                error_code = writer_error_code_3;
            end else begin
                error = 1'b0;
                error_code = 8'd0;
            end
        end
    end

    dau_axi_burst_reader #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32),
        .LENGTH_ALIGN_BITS(4)
    ) reader (
        .clk(clk),
        .rst(rst),
        .start(unit_start),
        .read_address(input_address),
        .read_length_bytes(input_length_bytes),
        .busy(reader_busy),
        .done(reader_done),
        .error(reader_error),
        .error_code(reader_error_code),
        .m_axi_araddr(rd_araddr),
        .m_axi_arlen(rd_arlen),
        .m_axi_arsize(rd_arsize),
        .m_axi_arburst(rd_arburst),
        .m_axi_arvalid(rd_arvalid),
        .m_axi_arready(rd_arready),
        .m_axi_rdata(rd_rdata),
        .m_axi_rresp(rd_rresp),
        .m_axi_rlast(rd_rlast),
        .m_axi_rvalid(rd_rvalid),
        .m_axi_rready(rd_rready),
        .stream_valid(scan_valid),
        .stream_ready(scan_ready),
        .stream_data(scan_data),
        .stream_last(scan_last),
        // boundary debug taps (BAR-mapped on hardware; unused in this sim)
        .dbg_first_stream_word(),
        .dbg_first_araddr(),
        .dbg_beats_while_idle(),
        .dbg_final_fifo_count()
    );

    dau_int32_range_partitioner #(
        .NUM_PARTITIONS(4)
    ) partitioner (
        .clk(clk),
        .rst(lane_rst),
        .cfg_splitters(cfg_splitters),
        .input_valid(scan_valid),
        .input_ready(scan_ready),
        .input_data(scan_data),
        .input_last(scan_last),
        .output_valid(part_out_valid),
        .output_ready(part_out_ready),
        .output_data(part_out_data),
        .output_last(part_out_last),
        .status_valid(part_status_valid),
        .status_ready(part_status_ready),
        .status_error(part_status_error),
        .status_error_code(part_status_error_code)
    );

    assign filt_out_valid_0 = part_out_valid[0];
    assign part_out_ready[0] = filt_out_ready_0;
    assign filt_out_data_0 = part_out_data[63:0];
    assign filt_out_last_0 = part_out_last[0];
    assign filt_status_valid_0 = part_status_valid[0];
    assign filt_status_error_0 = part_status_error[0];
    assign filt_status_error_code_0 = part_status_error_code[7:0];
    assign part_status_ready[0] = filt_status_ready_0;

    dau_int32_bitonic_sorter tile_0 (
        .clk(clk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_0),
        .input_ready(filt_out_ready_0),
        .input_data(filt_out_data_0),
        .input_last(filt_out_last_0),
        .output_valid(tile_out_valid_0),
        .output_ready(tile_out_ready_0),
        .output_data(tile_out_data_0),
        .output_last(tile_out_last_0),
        .status_valid(tile_status_valid_0),
        .status_ready(tile_status_ready_0),
        .status_error(tile_status_error_0),
        .status_error_code(tile_status_error_code_0),
        .sorted_count(tile_bar_count_0)
    );

    assign unit_status_valid_0 = tile_status_valid_0 || filt_status_valid_0;
    assign unit_status_error_0 = filt_status_valid_0 ? filt_status_error_0 : tile_status_error_0;
    assign unit_status_error_code_0 = filt_status_valid_0 ? filt_status_error_code_0 : tile_status_error_code_0;
    assign filt_status_ready_0 = unit_status_ready_0 && filt_status_valid_0;
    assign tile_status_ready_0 = unit_status_ready_0 && !filt_status_valid_0;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_0 (
        .clk(clk),
        .rst(rst),
        .start(unit_start),
        .output_address(lane_output_address_0),
        .busy(writer_busy_0),
        .done(writer_done_0),
        .error(writer_error_0),
        .error_code(writer_error_code_0),
        .result_length_bytes(lane_result_length_0),
        .m_axi_awaddr(wr_awaddr_0),
        .m_axi_awlen(wr_awlen_0),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_0),
        .m_axi_awready(wr_awready_0),
        .m_axi_wdata(wr_wdata_0),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_0),
        .m_axi_wvalid(wr_wvalid_0),
        .m_axi_wready(wr_wready_0),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_0),
        .m_axi_bready(wr_bready_0),
        .record_valid(tile_out_valid_0),
        .record_ready(tile_out_ready_0),
        .record_data(tile_out_data_0),
        .record_last(tile_out_last_0),
        .status_valid(unit_status_valid_0),
        .status_ready(unit_status_ready_0),
        .status_error(unit_status_error_0),
        .status_error_code(unit_status_error_code_0)
    );

    assign filt_out_valid_1 = part_out_valid[1];
    assign part_out_ready[1] = filt_out_ready_1;
    assign filt_out_data_1 = part_out_data[127:64];
    assign filt_out_last_1 = part_out_last[1];
    assign filt_status_valid_1 = part_status_valid[1];
    assign filt_status_error_1 = part_status_error[1];
    assign filt_status_error_code_1 = part_status_error_code[15:8];
    assign part_status_ready[1] = filt_status_ready_1;

    dau_int32_bitonic_sorter tile_1 (
        .clk(clk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_1),
        .input_ready(filt_out_ready_1),
        .input_data(filt_out_data_1),
        .input_last(filt_out_last_1),
        .output_valid(tile_out_valid_1),
        .output_ready(tile_out_ready_1),
        .output_data(tile_out_data_1),
        .output_last(tile_out_last_1),
        .status_valid(tile_status_valid_1),
        .status_ready(tile_status_ready_1),
        .status_error(tile_status_error_1),
        .status_error_code(tile_status_error_code_1),
        .sorted_count(tile_bar_count_1)
    );

    assign unit_status_valid_1 = tile_status_valid_1 || filt_status_valid_1;
    assign unit_status_error_1 = filt_status_valid_1 ? filt_status_error_1 : tile_status_error_1;
    assign unit_status_error_code_1 = filt_status_valid_1 ? filt_status_error_code_1 : tile_status_error_code_1;
    assign filt_status_ready_1 = unit_status_ready_1 && filt_status_valid_1;
    assign tile_status_ready_1 = unit_status_ready_1 && !filt_status_valid_1;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_1 (
        .clk(clk),
        .rst(rst),
        .start(unit_start),
        .output_address(lane_output_address_1),
        .busy(writer_busy_1),
        .done(writer_done_1),
        .error(writer_error_1),
        .error_code(writer_error_code_1),
        .result_length_bytes(lane_result_length_1),
        .m_axi_awaddr(wr_awaddr_1),
        .m_axi_awlen(wr_awlen_1),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_1),
        .m_axi_awready(wr_awready_1),
        .m_axi_wdata(wr_wdata_1),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_1),
        .m_axi_wvalid(wr_wvalid_1),
        .m_axi_wready(wr_wready_1),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_1),
        .m_axi_bready(wr_bready_1),
        .record_valid(tile_out_valid_1),
        .record_ready(tile_out_ready_1),
        .record_data(tile_out_data_1),
        .record_last(tile_out_last_1),
        .status_valid(unit_status_valid_1),
        .status_ready(unit_status_ready_1),
        .status_error(unit_status_error_1),
        .status_error_code(unit_status_error_code_1)
    );

    assign filt_out_valid_2 = part_out_valid[2];
    assign part_out_ready[2] = filt_out_ready_2;
    assign filt_out_data_2 = part_out_data[191:128];
    assign filt_out_last_2 = part_out_last[2];
    assign filt_status_valid_2 = part_status_valid[2];
    assign filt_status_error_2 = part_status_error[2];
    assign filt_status_error_code_2 = part_status_error_code[23:16];
    assign part_status_ready[2] = filt_status_ready_2;

    dau_int32_bitonic_sorter tile_2 (
        .clk(clk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_2),
        .input_ready(filt_out_ready_2),
        .input_data(filt_out_data_2),
        .input_last(filt_out_last_2),
        .output_valid(tile_out_valid_2),
        .output_ready(tile_out_ready_2),
        .output_data(tile_out_data_2),
        .output_last(tile_out_last_2),
        .status_valid(tile_status_valid_2),
        .status_ready(tile_status_ready_2),
        .status_error(tile_status_error_2),
        .status_error_code(tile_status_error_code_2),
        .sorted_count(tile_bar_count_2)
    );

    assign unit_status_valid_2 = tile_status_valid_2 || filt_status_valid_2;
    assign unit_status_error_2 = filt_status_valid_2 ? filt_status_error_2 : tile_status_error_2;
    assign unit_status_error_code_2 = filt_status_valid_2 ? filt_status_error_code_2 : tile_status_error_code_2;
    assign filt_status_ready_2 = unit_status_ready_2 && filt_status_valid_2;
    assign tile_status_ready_2 = unit_status_ready_2 && !filt_status_valid_2;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_2 (
        .clk(clk),
        .rst(rst),
        .start(unit_start),
        .output_address(lane_output_address_2),
        .busy(writer_busy_2),
        .done(writer_done_2),
        .error(writer_error_2),
        .error_code(writer_error_code_2),
        .result_length_bytes(lane_result_length_2),
        .m_axi_awaddr(wr_awaddr_2),
        .m_axi_awlen(wr_awlen_2),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_2),
        .m_axi_awready(wr_awready_2),
        .m_axi_wdata(wr_wdata_2),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_2),
        .m_axi_wvalid(wr_wvalid_2),
        .m_axi_wready(wr_wready_2),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_2),
        .m_axi_bready(wr_bready_2),
        .record_valid(tile_out_valid_2),
        .record_ready(tile_out_ready_2),
        .record_data(tile_out_data_2),
        .record_last(tile_out_last_2),
        .status_valid(unit_status_valid_2),
        .status_ready(unit_status_ready_2),
        .status_error(unit_status_error_2),
        .status_error_code(unit_status_error_code_2)
    );

    assign filt_out_valid_3 = part_out_valid[3];
    assign part_out_ready[3] = filt_out_ready_3;
    assign filt_out_data_3 = part_out_data[255:192];
    assign filt_out_last_3 = part_out_last[3];
    assign filt_status_valid_3 = part_status_valid[3];
    assign filt_status_error_3 = part_status_error[3];
    assign filt_status_error_code_3 = part_status_error_code[31:24];
    assign part_status_ready[3] = filt_status_ready_3;

    dau_int32_bitonic_sorter tile_3 (
        .clk(clk),
        .rst(lane_rst),
        .input_valid(filt_out_valid_3),
        .input_ready(filt_out_ready_3),
        .input_data(filt_out_data_3),
        .input_last(filt_out_last_3),
        .output_valid(tile_out_valid_3),
        .output_ready(tile_out_ready_3),
        .output_data(tile_out_data_3),
        .output_last(tile_out_last_3),
        .status_valid(tile_status_valid_3),
        .status_ready(tile_status_ready_3),
        .status_error(tile_status_error_3),
        .status_error_code(tile_status_error_code_3),
        .sorted_count(tile_bar_count_3)
    );

    assign unit_status_valid_3 = tile_status_valid_3 || filt_status_valid_3;
    assign unit_status_error_3 = filt_status_valid_3 ? filt_status_error_3 : tile_status_error_3;
    assign unit_status_error_code_3 = filt_status_valid_3 ? filt_status_error_code_3 : tile_status_error_code_3;
    assign filt_status_ready_3 = unit_status_ready_3 && filt_status_valid_3;
    assign tile_status_ready_3 = unit_status_ready_3 && !filt_status_valid_3;

    dau_axi_record_writer #(
        .ADDR_WIDTH(32),
        .BURST_BEATS(32)
    ) writer_3 (
        .clk(clk),
        .rst(rst),
        .start(unit_start),
        .output_address(lane_output_address_3),
        .busy(writer_busy_3),
        .done(writer_done_3),
        .error(writer_error_3),
        .error_code(writer_error_code_3),
        .result_length_bytes(lane_result_length_3),
        .m_axi_awaddr(wr_awaddr_3),
        .m_axi_awlen(wr_awlen_3),
        .m_axi_awsize(),
        .m_axi_awburst(),
        .m_axi_awvalid(wr_awvalid_3),
        .m_axi_awready(wr_awready_3),
        .m_axi_wdata(wr_wdata_3),
        .m_axi_wstrb(),
        .m_axi_wlast(wr_wlast_3),
        .m_axi_wvalid(wr_wvalid_3),
        .m_axi_wready(wr_wready_3),
        .m_axi_bresp(wr_bresp),
        .m_axi_bvalid(wr_bvalid_3),
        .m_axi_bready(wr_bready_3),
        .record_valid(tile_out_valid_3),
        .record_ready(tile_out_ready_3),
        .record_data(tile_out_data_3),
        .record_last(tile_out_last_3),
        .status_valid(unit_status_valid_3),
        .status_ready(unit_status_ready_3),
        .status_error(unit_status_error_3),
        .status_error_code(unit_status_error_code_3)
    );

    assign wr_awaddr_flat[31:0] = wr_awaddr_0;
    assign wr_awlen_flat[7:0] = wr_awlen_0;
    assign wr_awvalid_flat[0] = wr_awvalid_0;
    assign wr_awready_0 = wr_awready_flat[0];
    assign wr_wdata_flat[63:0] = wr_wdata_0;
    assign wr_wlast_flat[0] = wr_wlast_0;
    assign wr_wvalid_flat[0] = wr_wvalid_0;
    assign wr_wready_0 = wr_wready_flat[0];
    assign wr_bvalid_0 = wr_bvalid_flat[0];
    assign wr_bready_flat[0] = wr_bready_0;
    assign wr_awaddr_flat[63:32] = wr_awaddr_1;
    assign wr_awlen_flat[15:8] = wr_awlen_1;
    assign wr_awvalid_flat[1] = wr_awvalid_1;
    assign wr_awready_1 = wr_awready_flat[1];
    assign wr_wdata_flat[127:64] = wr_wdata_1;
    assign wr_wlast_flat[1] = wr_wlast_1;
    assign wr_wvalid_flat[1] = wr_wvalid_1;
    assign wr_wready_1 = wr_wready_flat[1];
    assign wr_bvalid_1 = wr_bvalid_flat[1];
    assign wr_bready_flat[1] = wr_bready_1;
    assign wr_awaddr_flat[95:64] = wr_awaddr_2;
    assign wr_awlen_flat[23:16] = wr_awlen_2;
    assign wr_awvalid_flat[2] = wr_awvalid_2;
    assign wr_awready_2 = wr_awready_flat[2];
    assign wr_wdata_flat[191:128] = wr_wdata_2;
    assign wr_wlast_flat[2] = wr_wlast_2;
    assign wr_wvalid_flat[2] = wr_wvalid_2;
    assign wr_wready_2 = wr_wready_flat[2];
    assign wr_bvalid_2 = wr_bvalid_flat[2];
    assign wr_bready_flat[2] = wr_bready_2;
    assign wr_awaddr_flat[127:96] = wr_awaddr_3;
    assign wr_awlen_flat[31:24] = wr_awlen_3;
    assign wr_awvalid_flat[3] = wr_awvalid_3;
    assign wr_awready_3 = wr_awready_flat[3];
    assign wr_wdata_flat[255:192] = wr_wdata_3;
    assign wr_wlast_flat[3] = wr_wlast_3;
    assign wr_wvalid_flat[3] = wr_wvalid_3;
    assign wr_wready_3 = wr_wready_flat[3];
    assign wr_bvalid_3 = wr_bvalid_flat[3];
    assign wr_bready_flat[3] = wr_bready_3;

    dau_axi_write_mux #(
        .NUM_INPUTS(4),
        .ADDR_WIDTH(32)
    ) write_mux (
        .clk(clk),
        .rst(rst),
        .s_awaddr(wr_awaddr_flat),
        .s_awlen(wr_awlen_flat),
        .s_awvalid(wr_awvalid_flat),
        .s_awready(wr_awready_flat),
        .s_wdata(wr_wdata_flat),
        .s_wlast(wr_wlast_flat),
        .s_wvalid(wr_wvalid_flat),
        .s_wready(wr_wready_flat),
        .s_bresp(wr_bresp),
        .s_bvalid(wr_bvalid_flat),
        .s_bready(wr_bready_flat),
        .m_axi_awaddr(mx_awaddr),
        .m_axi_awlen(mx_awlen),
        .m_axi_awsize(mx_awsize),
        .m_axi_awburst(mx_awburst),
        .m_axi_awvalid(mx_awvalid),
        .m_axi_awready(mx_awready),
        .m_axi_wdata(mx_wdata),
        .m_axi_wstrb(mx_wstrb),
        .m_axi_wlast(mx_wlast),
        .m_axi_wvalid(mx_wvalid),
        .m_axi_wready(mx_wready),
        .m_axi_bresp(mx_bresp),
        .m_axi_bvalid(mx_bvalid),
        .m_axi_bready(mx_bready)
    );

    dau_axi_ram_sim #(
        .ADDR_WIDTH(32),
        .MEM_WORDS(65536),
        .READ_LATENCY(4)
    ) ram (
        .clk(clk),
        .rst(rst),
        .s_axi_araddr(rd_araddr),
        .s_axi_arlen(rd_arlen),
        .s_axi_arsize(rd_arsize),
        .s_axi_arburst(rd_arburst),
        .s_axi_arvalid(rd_arvalid),
        .s_axi_arready(rd_arready),
        .s_axi_rdata(rd_rdata),
        .s_axi_rresp(rd_rresp),
        .s_axi_rlast(rd_rlast),
        .s_axi_rvalid(rd_rvalid),
        .s_axi_rready(rd_rready),
        .s_axi_awaddr(mx_awaddr),
        .s_axi_awlen(mx_awlen),
        .s_axi_awsize(mx_awsize),
        .s_axi_awburst(mx_awburst),
        .s_axi_awvalid(mx_awvalid),
        .s_axi_awready(mx_awready),
        .s_axi_wdata(mx_wdata),
        .s_axi_wstrb(mx_wstrb),
        .s_axi_wlast(mx_wlast),
        .s_axi_wvalid(mx_wvalid),
        .s_axi_wready(mx_wready),
        .s_axi_bresp(mx_bresp),
        .s_axi_bvalid(mx_bvalid),
        .s_axi_bready(mx_bready),
        .bd_write(bd_write),
        .bd_index(bd_index),
        .bd_wdata(bd_wdata),
        .bd_rdata(bd_rdata)
    );

    always @(posedge clk) begin
        if (rst) begin
            prev_done <= 1'b1;
            pipeline_error_reset <= 1'b0;
            length_fail <= 1'b0;
            lane_bar_count_0 <= 64'd0;
            lane_bar_count_1 <= 64'd0;
            lane_bar_count_2 <= 64'd0;
            lane_bar_count_3 <= 64'd0;
        end else begin
            prev_done <= done;
            pipeline_error_reset <= done && !prev_done && error;
            if (start) begin
                length_fail <= !length_ok;
                lane_bar_count_0 <= 64'd0;
                lane_bar_count_1 <= 64'd0;
                lane_bar_count_2 <= 64'd0;
                lane_bar_count_3 <= 64'd0;
            end
            if (tile_status_valid_0 && tile_status_ready_0) begin
                lane_bar_count_0 <= tile_bar_count_0;
            end
            if (tile_status_valid_1 && tile_status_ready_1) begin
                lane_bar_count_1 <= tile_bar_count_1;
            end
            if (tile_status_valid_2 && tile_status_ready_2) begin
                lane_bar_count_2 <= tile_bar_count_2;
            end
            if (tile_status_valid_3 && tile_status_ready_3) begin
                lane_bar_count_3 <= tile_bar_count_3;
            end
        end
    end
endmodule

`default_nettype wire
