"""DAU platform variant 1 (dpv1) MM job shell project generation.

Productization of the proven bring-up flow: emits the
Vivado project Tcl, constraints, and the lane-swizzle implementation hook for
the memory-mapped DAU job shell on the DAU platform variant 1 (dpv1) (XC7A200T over Thunderbolt
XDMA). Hardware rules baked in (see dau-docs GUIDELINES):

- the PCIe personality must mirror the proven shell exactly: 64-bit
  prefetchable BARs (the Thunderbolt bridge only forwards the 64-bit
  prefetchable window; 32-bit non-prefetch BARs enumerate but all memory
  reads return all-ones), 128 KB AXI-Lite BAR, QPLL1 GTP clocking;
- the reversed lane-to-GT-channel mapping is applied as a pre-opt_design
  implementation hook (XDC-time LOCs conflict with the IP's internal BEL/LOC
  constraints) and verified post-route;
- BRAM staging addresses follow DEFAULT_STREAM_JOB_REGISTER_CONTRACT.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

DPV1_PART = "xc7a200tfbg484-2"

# lane index -> GTPE2 channel site (reversed lane order on the DAU platform variant 1 (dpv1))
GT_LANE_SWIZZLE = ((3, "GTPE2_CHANNEL_X0Y7"), (0, "GTPE2_CHANNEL_X0Y6"), (2, "GTPE2_CHANNEL_X0Y5"), (1, "GTPE2_CHANNEL_X0Y4"))

# XDMA personality: byte-for-byte the proven shell's PCIe-facing configuration.
DPV1_XDMA_PERSONALITY = {
    # every value_src=user parameter from the proven bring-up core's XCI
    # (xdma 4.1, extracted 2026-07-09), applied verbatim: fresh 2025.x
    # customizations with only the "obvious" subset were memory-dead on
    # hardware (BARs enumerate, all reads 0xFFFFFFFF), so the personality is
    # the complete user-set customization, not a hand-picked one.
    "mode_selection": "Advanced",
    "pl_link_cap_max_link_width": "X4",
    "pl_link_cap_max_link_speed": "5.0_GT/s",
    "axi_data_width": "128_bit",
    "axisten_freq": "125",
    "xdma_axi_intf_mm": "AXI_Memory_Mapped",
    "xdma_rnum_chnl": "1",
    "xdma_wnum_chnl": "1",
    "xdma_sts_ports": "false",
    "axilite_master_en": "true",
    "axilite_master_size": "128",
    "axilite_master_scale": "Kilobytes",
    "axil_master_64bit_en": "true",
    "axil_master_prefetchable": "true",
    "xdma_pcie_64bit_en": "true",
    "xdma_pcie_prefetchable": "true",
    "plltype": "QPLL1",
    "cfg_mgmt_if": "false",
    "copy_pf0": "true",
    "runbit_fix": "false",
    "en_ext_ch_gt_drp": "false",
    "en_pcie_drp": "false",
    "en_transceiver_status_ports": "false",
    "enable_gen4": "false",
    "vendor_id": "10EE",
    "pf0_device_id": "7011",
    "pf0_Use_Class_Code_Lookup_Assistant": "false",
    "pf0_base_class_menu": "Device_was_built_before_Class_Code_definitions_were_finalized",
    "pf0_sub_class_interface_menu": "All_currently_implemented_devices_except_VGA-compatible_devices",
    "pf0_class_code": "120000",
    "pf0_class_code_base": "12",
    "pf0_class_code_sub": "00",
    "pf0_class_code_interface": "00",
    "pf0_subsystem_vendor_id": "0",
    "pf0_subsystem_id": "0",
    "pf0_msix_cap_table_bir": "BAR_3:2",
    "pf0_msix_cap_pba_bir": "BAR_3:2",
    "pf1_msix_cap_table_size": "000",
    "pf1_msix_cap_table_offset": "00000000",
    "pf1_msix_cap_pba_offset": "00000000",
    "PF0_DEVICE_ID_mqdma": "9024",
    "PF2_DEVICE_ID_mqdma": "9024",
    "PF3_DEVICE_ID_mqdma": "9024",
    "PF0_SRIOV_VF_DEVICE_ID": "0000",
    "PF1_SRIOV_VF_DEVICE_ID": "A134",
    "PF2_SRIOV_VF_DEVICE_ID": "A234",
    "PF3_SRIOV_VF_DEVICE_ID": "A334",
}


@dataclass(frozen=True)
class MmJobShellRequest:
    """Inputs for generating the MM job shell project. The caller supplies
    the generated binding sources as (filename, text) pairs — dau-build is
    generic platform integration and generates the *project*, never the
    domain HDL. Staging addresses are plain values; DAU flows pass their
    register-contract numbers."""

    output_root: Path
    hdl_sources: tuple[Path, ...]
    generated_sources: tuple[tuple[str, str], ...]
    top_module: str
    part: str = DPV1_PART
    input_buffer_address: int = 0x0000_0000
    output_buffer_address: int = 0x0010_0000
    register_window_offset: int = 0x0000_1000
    input_bram_bytes: int = 0x0002_0000  # 128 KiB
    output_bram_bytes: int = 0x0000_1000  # 4 KiB
    jobs: int = 12


def gt_lane_swizzle_hook_tcl() -> str:
    """Pre-opt_design hook applying the DAU platform variant 1 (dpv1) lane swizzle, version-robust
    across XDMA internal hierarchy renames."""
    swizzle_pairs = " ".join(f"{lane} {channel}" for lane, channel in GT_LANE_SWIZZLE)
    return f"""# GENERATED by dau_build.dpv1_shell — do not edit.
# Pre-opt_design implementation hook: apply the DAU platform variant 1 (dpv1) PCIe lane swizzle
# after the IP's own XDC constraints, per CRITICAL WARNING 18-4427 guidance.
set swizzle {{{swizzle_pairs}}}
set lane_cells [dict create]
set gts [get_cells -hierarchical -quiet -filter {{REF_NAME == GTPE2_CHANNEL || ORIG_REF_NAME == GTPE2_CHANNEL}}]
foreach cell $gts {{
    if {{[regexp {{pipe_lane\\[(\\d+)\\]}} $cell -> lane]}} {{
        dict set lane_cells $lane $cell
    }}
}}
if {{[dict size $lane_cells] != 4}} {{
    error "gt_lane_swizzle: expected 4 GTPE2_CHANNEL lane cells, found [dict size $lane_cells]"
}}
# two-phase: release every lane's LOC first, then place — interleaved
# reset/set hits "bel is occupied" when a target site is still held by a
# not-yet-processed lane (Vivado 12-2285, a CRITICAL WARNING that silently
# leaves lanes crossed)
foreach {{lane channel}} $swizzle {{
    reset_property -quiet LOC [dict get $lane_cells $lane]
}}
foreach {{lane channel}} $swizzle {{
    set cell [dict get $lane_cells $lane]
    set_property LOC $channel $cell
    set got [get_property LOC $cell]
    if {{$got ne $channel}} {{
        error "gt_lane_swizzle: pipe_lane\\[$lane\\] LOC is '$got', wanted $channel"
    }}
    puts "gt_lane_swizzle: pipe_lane\\[$lane\\] ($cell) -> $channel"
}}
"""


def dpv1_constraints_xdc() -> str:
    """Pin constraints for the MM job shell (no GT LOCs here — the swizzle is
    applied by the implementation hook)."""
    return """# GENERATED by dau_build.dpv1_shell — do not edit.
# DAU platform variant 1 (dpv1) pin constraints. GT channel LOCs (the lane swizzle) are applied by
# the pre-opt_design implementation hook, never here: XDC-time LOCs conflict
# with the XDMA IP's internal BEL/LOC constraints.

set_property PACKAGE_PIN A10 [get_ports {pcie_mgt_rxn[0]}]
set_property PACKAGE_PIN B10 [get_ports {pcie_mgt_rxp[0]}]
set_property PACKAGE_PIN A6 [get_ports {pcie_mgt_txn[0]}]
set_property PACKAGE_PIN B6 [get_ports {pcie_mgt_txp[0]}]
set_property PACKAGE_PIN A8 [get_ports {pcie_mgt_rxn[1]}]
set_property PACKAGE_PIN B8 [get_ports {pcie_mgt_rxp[1]}]
set_property PACKAGE_PIN A4 [get_ports {pcie_mgt_txn[1]}]
set_property PACKAGE_PIN B4 [get_ports {pcie_mgt_txp[1]}]
set_property PACKAGE_PIN C11 [get_ports {pcie_mgt_rxn[2]}]
set_property PACKAGE_PIN D11 [get_ports {pcie_mgt_rxp[2]}]
set_property PACKAGE_PIN C5 [get_ports {pcie_mgt_txn[2]}]
set_property PACKAGE_PIN D5 [get_ports {pcie_mgt_txp[2]}]
set_property PACKAGE_PIN C9 [get_ports {pcie_mgt_rxn[3]}]
set_property PACKAGE_PIN D9 [get_ports {pcie_mgt_rxp[3]}]
set_property PACKAGE_PIN C7 [get_ports {pcie_mgt_txn[3]}]
set_property PACKAGE_PIN D7 [get_ports {pcie_mgt_txp[3]}]

set_property PACKAGE_PIN F6 [get_ports {pcie_clkin_clk_p[0]}]
set_property PACKAGE_PIN E6 [get_ports {pcie_clkin_clk_n[0]}]

set_property PACKAGE_PIN J1 [get_ports pci_reset]
set_property IOSTANDARD LVCMOS33 [get_ports pci_reset]
set_false_path -from [get_ports pci_reset]

set_property PACKAGE_PIN G1 [get_ports {pcie_clkreq_l[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcie_clkreq_l[0]}]

set_property PACKAGE_PIN M1 [get_ports {LED_M2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_M2[0]}]
set_property PULLUP true [get_ports {LED_M2[0]}]
set_property DRIVE 8 [get_ports {LED_M2[0]}]

set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
"""


def mm_job_shell_project_tcl(request: MmJobShellRequest) -> str:
    """Full batch-mode project script: create project, build the XDMA MM BD
    with BRAM staging at the register-contract addresses, synthesize and
    implement with the swizzle hook, verify post-route, emit the bitstream."""
    xdma_config = " \\\n".join(f"    CONFIG.{key} {{{value}}}" for key, value in DPV1_XDMA_PERSONALITY.items())
    generated_paths = tuple(request.output_root / name for name, _ in request.generated_sources)
    sources = " \\\n".join(f'    "{path.as_posix()}"' for path in (*request.hdl_sources, *generated_paths))
    sv_typing = "\n".join(
        f'set_property file_type SystemVerilog [get_files "{path.as_posix()}"]' for path in request.hdl_sources if path.suffix == ".sv"
    )
    swizzle_pairs = " ".join(f"{lane} {channel}" for lane, channel in GT_LANE_SWIZZLE)
    return f"""# GENERATED by dau_build.dpv1_shell — do not edit.
# DAU MM job shell: XDMA (memory-mapped, proven DAU platform variant 1 (dpv1) PCIe personality)
# with BRAM staging at the stream-job contract addresses.
set origin_dir [file dirname [file normalize [info script]]]

create_project -force project_mm "$origin_dir/project_mm" -part {request.part}

add_files [list \\
{sources} \\
]
{sv_typing}

add_files -fileset constrs_1 "$origin_dir/constraints.xdc"
set_property PROCESSING_ORDER EARLY [get_files "$origin_dir/constraints.xdc"]

create_bd_design Top

set xdma_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:xdma xdma_0]
set_property -dict [list \\
{xdma_config} \\
] $xdma_0

set refclk_buf [create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf refclk_buf]
set_property CONFIG.C_BUF_TYPE {{IBUFDSGTE}} $refclk_buf
set clkreq_low [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant clkreq_low]
set_property -dict [list CONFIG.CONST_VAL {{0}} CONFIG.CONST_WIDTH {{1}}] $clkreq_low

make_bd_intf_pins_external [get_bd_intf_pins xdma_0/pcie_mgt]
set_property name pcie_mgt [get_bd_intf_ports pcie_mgt_0]
set pcie_clkin [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 pcie_clkin]
set_property CONFIG.FREQ_HZ {{100000000}} $pcie_clkin
connect_bd_intf_net $pcie_clkin [get_bd_intf_pins refclk_buf/CLK_IN_D]
set pci_reset [create_bd_port -dir I -type rst pci_reset]
set_property CONFIG.POLARITY {{ACTIVE_LOW}} $pci_reset
connect_bd_net $pci_reset [get_bd_pins xdma_0/sys_rst_n]
set clkreq_port [create_bd_port -dir O -from 0 -to 0 pcie_clkreq_l]
connect_bd_net [get_bd_pins clkreq_low/dout] $clkreq_port
set led_port [create_bd_port -dir O -from 0 -to 0 LED_M2]
connect_bd_net [get_bd_pins xdma_0/user_lnk_up] $led_port
connect_bd_net [get_bd_pins refclk_buf/IBUF_OUT] [get_bd_pins xdma_0/sys_clk]

set dau_job [create_bd_cell -type module -reference {request.top_module} {request.top_module}_0]

set bram_ctrl_in [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl bram_ctrl_in]
set_property -dict [list CONFIG.DATA_WIDTH {{64}} CONFIG.SINGLE_PORT_BRAM {{1}}] $bram_ctrl_in
set bram_ctrl_out [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl bram_ctrl_out]
set_property -dict [list CONFIG.DATA_WIDTH {{64}} CONFIG.SINGLE_PORT_BRAM {{1}}] $bram_ctrl_out
set mem_in [create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen mem_in]
set_property -dict [list CONFIG.Memory_Type {{True_Dual_Port_RAM}} CONFIG.use_bram_block {{BRAM_Controller}} CONFIG.Enable_B {{Use_ENB_Pin}}] $mem_in
set mem_out [create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen mem_out]
set_property -dict [list CONFIG.Memory_Type {{True_Dual_Port_RAM}} CONFIG.use_bram_block {{BRAM_Controller}} CONFIG.Enable_B {{Use_ENB_Pin}}] $mem_out

connect_bd_intf_net [get_bd_intf_pins bram_ctrl_in/BRAM_PORTA] [get_bd_intf_pins mem_in/BRAM_PORTA]
connect_bd_intf_net [get_bd_intf_pins {request.top_module}_0/BRAM_IN] [get_bd_intf_pins mem_in/BRAM_PORTB]
connect_bd_intf_net [get_bd_intf_pins bram_ctrl_out/BRAM_PORTA] [get_bd_intf_pins mem_out/BRAM_PORTA]
connect_bd_intf_net [get_bd_intf_pins {request.top_module}_0/BRAM_OUT] [get_bd_intf_pins mem_out/BRAM_PORTB]

set smc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smc]
set_property -dict [list CONFIG.NUM_SI {{1}} CONFIG.NUM_MI {{2}}] $smc
set dw_in [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dwidth_converter dw_in]
set_property -dict [list CONFIG.SI_DATA_WIDTH {{128}} CONFIG.MI_DATA_WIDTH {{64}}] $dw_in
set dw_out [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dwidth_converter dw_out]
set_property -dict [list CONFIG.SI_DATA_WIDTH {{128}} CONFIG.MI_DATA_WIDTH {{64}}] $dw_out
connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI] [get_bd_intf_pins smc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins smc/M00_AXI] [get_bd_intf_pins dw_in/S_AXI]
connect_bd_intf_net [get_bd_intf_pins dw_in/M_AXI] [get_bd_intf_pins bram_ctrl_in/S_AXI]
connect_bd_intf_net [get_bd_intf_pins smc/M01_AXI] [get_bd_intf_pins dw_out/S_AXI]
connect_bd_intf_net [get_bd_intf_pins dw_out/M_AXI] [get_bd_intf_pins bram_ctrl_out/S_AXI]

# the proven shell routes M_AXI_LITE through an interconnect, never directly
# into a register block; smc_lite mirrors that (pipelined, spec-strict
# handshakes between the XDMA AXI-Lite master and the module reference)
set smc_lite [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smc_lite]
set_property -dict [list CONFIG.NUM_SI {{1}} CONFIG.NUM_MI {{1}}] $smc_lite
connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI_LITE] [get_bd_intf_pins smc_lite/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins smc_lite/M00_AXI] [get_bd_intf_pins {request.top_module}_0/S_AXI]

connect_bd_net [get_bd_pins xdma_0/axi_aclk] \\
    [get_bd_pins smc/aclk] [get_bd_pins smc_lite/aclk] [get_bd_pins bram_ctrl_in/s_axi_aclk] [get_bd_pins bram_ctrl_out/s_axi_aclk] \\
    [get_bd_pins dw_in/s_axi_aclk] [get_bd_pins dw_out/s_axi_aclk] \\
    [get_bd_pins {request.top_module}_0/s_axi_aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] \\
    [get_bd_pins smc/aresetn] [get_bd_pins smc_lite/aresetn] [get_bd_pins bram_ctrl_in/s_axi_aresetn] [get_bd_pins bram_ctrl_out/s_axi_aresetn] \\
    [get_bd_pins dw_in/s_axi_aresetn] [get_bd_pins dw_out/s_axi_aresetn] \\
    [get_bd_pins {request.top_module}_0/s_axi_aresetn]

assign_bd_address -offset 0x{request.input_buffer_address:08X} -range 0x{request.input_bram_bytes:08X} -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs bram_ctrl_in/S_AXI/*] -force
assign_bd_address -offset 0x{request.output_buffer_address:08X} -range 0x{request.output_bram_bytes:08X} -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs bram_ctrl_out/S_AXI/*] -force
assign_bd_address -offset 0x{request.register_window_offset:08X} -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs {request.top_module}_0/S_AXI/*] -force

validate_bd_design
save_bd_design

make_wrapper -files [get_files [get_property FILE_NAME [get_bd_designs Top]]] -top
add_files -norecurse "$origin_dir/project_mm/project_mm.gen/sources_1/bd/Top/hdl/Top_wrapper.v"
set_property top Top_wrapper [current_fileset]
update_compile_order -fileset sources_1

launch_runs synth_1 -jobs {request.jobs}
wait_on_run synth_1
if {{[get_property PROGRESS [get_runs synth_1]] != "100%"}} {{
    puts "DAU_MM_JOB_BUILD_FAILED synthesis"
    exit 1
}}

set_property STEPS.OPT_DESIGN.TCL.PRE "$origin_dir/gt_lane_swizzle.tcl" [get_runs impl_1]
launch_runs impl_1 -to_step write_bitstream -jobs {request.jobs}
wait_on_run impl_1
if {{[get_property PROGRESS [get_runs impl_1]] != "100%"}} {{
    puts "DAU_MM_JOB_BUILD_FAILED implementation"
    exit 1
}}
open_run impl_1
report_utilization -file "$origin_dir/utilization_mm.rpt"
report_timing_summary -file "$origin_dir/timing_mm.rpt"

set routed_lanes [dict create]
foreach cell [get_cells -hierarchical -quiet -filter {{REF_NAME == GTPE2_CHANNEL || ORIG_REF_NAME == GTPE2_CHANNEL}}] {{
    if {{[regexp {{pipe_lane\\[(\\d+)\\]}} $cell -> lane]}} {{
        dict set routed_lanes $lane [get_property LOC $cell]
    }}
}}
foreach {{lane channel}} {{{swizzle_pairs}}} {{
    if {{![dict exists $routed_lanes $lane] || [dict get $routed_lanes $lane] != $channel}} {{
        puts "DAU_MM_JOB_BUILD_FAILED lane $lane misplaced (expected $channel)"
        exit 1
    }}
}}
puts "lane swizzle verified"

set wns [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1 -setup]]
file copy -force "$origin_dir/project_mm/project_mm.runs/impl_1/Top_wrapper.bit" "$origin_dir/dau_mm_job.bit"
puts "DAU_MM_JOB_BUILD_OK wns=$wns"
exit 0
"""


def write_mm_job_shell_artifacts(request: MmJobShellRequest) -> tuple[Path, ...]:
    """Write the caller-generated sources, project Tcl, constraints, and
    swizzle hook into ``request.output_root``; returns the written paths."""
    request.output_root.mkdir(parents=True, exist_ok=True)
    written = []

    for name, text in request.generated_sources:
        path = request.output_root / name
        path.write_text(text)
        written.append(path)

    for name, text in (
        ("build_mm_job.tcl", mm_job_shell_project_tcl(request)),
        ("constraints.xdc", dpv1_constraints_xdc()),
        ("gt_lane_swizzle.tcl", gt_lane_swizzle_hook_tcl()),
    ):
        path = request.output_root / name
        path.write_text(text)
        written.append(path)
    return tuple(written)
