"""Generated shell binding tops.

dau-build owns the HDL that binds dau-core components to a shell: register
apertures, staged-job wiring, and stream-interface shims. dau-core keeps the
reusable pieces (tiles, the BRAM job runner, identity registers); these
generators emit the plain-Verilog tops that connect them to XDMA shells.
Plain Verilog because Vivado block-design module references reject
SystemVerilog tops.

Generated output is behavior-tested: dau-build's test suite runs the composed
cocotb bench against freshly generated sources (see test_shell_tops.py), so
codegen changes cannot silently break the register/stream contract.
"""

from __future__ import annotations

from dau_core.registers import RegisterOffset

_STREAM_TILE_PORTS = (
    ("input_valid", "tile_input_valid"),
    ("input_ready", "tile_input_ready"),
    ("input_data", "tile_input_data"),
    ("input_last", "tile_input_last"),
    ("output_valid", "tile_output_valid"),
    ("output_ready", "tile_output_ready"),
    ("output_data", "tile_output_data"),
    ("output_last", "tile_output_last"),
    ("status_valid", "tile_status_valid"),
    ("status_ready", "tile_status_ready"),
    ("status_error", "tile_status_error"),
    ("status_error_code", "tile_status_error_code"),
)


def generate_mm_stream_job_top_sv(
    *,
    module_name: str = "dau_mm_stream_job",
    tile_module: str = "dau_int32_record_batch_aggregation",
    operator_bitmap: int = 0x0000_001E,
    input_addr_width: int = 14,
    output_addr_width: int = 9,
) -> str:
    """MM-shell stream job top: AXI-Lite register aperture (identity + the
    stream-job contract) driving the BRAM-staged job runner and the selected
    stream tile. BRAM ports are byte-addressed for axi_bram_ctrl pairing."""
    tile_wiring = "\n".join(f"        .{tile_port}({wire})," for tile_port, wire in _STREAM_TILE_PORTS).rstrip(",")
    return f"""`default_nettype none

// GENERATED by dau_build.shell_tops.generate_mm_stream_job_top_sv — do not
// edit. Binds {tile_module} behind the DAU stream-job register contract with
// BRAM staging. Plain-Verilog top (BD module references require it).
module {module_name} #(
    parameter [31:0] OPERATOR_BITMAP = 32'h{operator_bitmap:08X},
    parameter INPUT_ADDR_WIDTH = {input_addr_width},
    parameter OUTPUT_ADDR_WIDTH = {output_addr_width}
) (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s_axi_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S_AXI, ASSOCIATED_RESET s_axi_aresetn" *)
    input wire s_axi_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s_axi_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input wire s_axi_aresetn,

    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S_AXI, PROTOCOL AXI4LITE, DATA_WIDTH 32, ADDR_WIDTH 16, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1" *)
    input wire [15:0] s_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWVALID" *)
    input wire s_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWREADY" *)
    output reg s_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WDATA" *)
    input wire [31:0] s_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WSTRB" *)
    input wire [3:0] s_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WVALID" *)
    input wire s_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WREADY" *)
    output reg s_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BRESP" *)
    output wire [1:0] s_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BVALID" *)
    output reg s_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BREADY" *)
    input wire s_axi_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARADDR" *)
    input wire [15:0] s_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARVALID" *)
    input wire s_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARREADY" *)
    output reg s_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RDATA" *)
    output reg [31:0] s_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RRESP" *)
    output wire [1:0] s_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RVALID" *)
    output reg s_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RREADY" *)
    input wire s_axi_rready,

    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN ADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME BRAM_IN, MASTER_TYPE BRAM_CTRL, MEM_WIDTH 64, MEM_SIZE {(1 << input_addr_width) * 8}, READ_WRITE_MODE READ_WRITE" *)
    output wire [31:0] bram_in_addr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN CLK" *)
    output wire bram_in_clk,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN DIN" *)
    output wire [63:0] bram_in_din,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN DOUT" *)
    input wire [63:0] bram_in_dout,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN EN" *)
    output wire bram_in_en,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN RST" *)
    output wire bram_in_rst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN WE" *)
    output wire [7:0] bram_in_we,

    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT ADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME BRAM_OUT, MASTER_TYPE BRAM_CTRL, MEM_WIDTH 64, MEM_SIZE {(1 << output_addr_width) * 8}, READ_WRITE_MODE READ_WRITE" *)
    output wire [31:0] bram_out_addr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT CLK" *)
    output wire bram_out_clk,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT DIN" *)
    output wire [63:0] bram_out_din,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT DOUT" *)
    input wire [63:0] bram_out_dout,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT EN" *)
    output wire bram_out_en,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT RST" *)
    output wire bram_out_rst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT WE" *)
    output wire [7:0] bram_out_we
);
    // window-relative decode: the register window sits at a 4 KiB-aligned BAR
    // offset (contract register_window_offset), so only addr[11:0] selects a
    // register — full-width compares against the raw offsets never match on
    // hardware, where the AXI address carries the BAR offset
    localparam [11:0] ADDR_LAST_ERROR = 12'h{int(RegisterOffset.LAST_ERROR):03X};
    localparam [11:0] ADDR_JOB_CONTROL = 12'h{int(RegisterOffset.JOB_CONTROL):03X};
    localparam [11:0] ADDR_JOB_STATUS = 12'h{int(RegisterOffset.JOB_STATUS):03X};
    localparam [11:0] ADDR_INPUT_LENGTH_LOW = 12'h{int(RegisterOffset.INPUT_LENGTH_LOW):03X};
    localparam [11:0] ADDR_RESULT_LENGTH_LOW = 12'h{int(RegisterOffset.RESULT_LENGTH_LOW):03X};
    localparam [11:0] ADDR_RESULT_LENGTH_HIGH = 12'h{int(RegisterOffset.RESULT_LENGTH_HIGH):03X};

    wire write_fire;
    wire read_fire;
    wire [15:0] selected_addr;
    wire [31:0] identity_rdata;
    wire [31:0] reset_request_unused;

    reg [31:0] input_length_bytes;
    reg job_start;

    wire job_busy;
    wire job_done;
    wire job_error;
    wire [7:0] job_error_code;
    wire [31:0] result_length_bytes;
    wire [INPUT_ADDR_WIDTH-1:0] job_in_word_addr;
    wire [OUTPUT_ADDR_WIDTH-1:0] job_out_word_addr;
    wire job_in_en;
    wire job_out_en;
    wire job_out_we;
    wire [63:0] job_out_din;

    wire tile_input_valid;
    wire tile_input_ready;
    wire [63:0] tile_input_data;
    wire tile_input_last;
    wire tile_output_valid;
    wire tile_output_ready;
    wire [63:0] tile_output_data;
    wire tile_output_last;
    wire tile_status_valid;
    wire tile_status_ready;
    wire tile_status_error;
    wire [7:0] tile_status_error_code;

    assign write_fire = !s_axi_bvalid && s_axi_awvalid && s_axi_wvalid;
    assign read_fire = !write_fire && !s_axi_rvalid && s_axi_arvalid;
    assign selected_addr = write_fire ? s_axi_awaddr : s_axi_araddr;
    assign s_axi_bresp = 2'b00;
    assign s_axi_rresp = 2'b00;

    // byte addressing toward axi_bram_ctrl-paired block RAM
    assign bram_in_addr = {{{{(29 - INPUT_ADDR_WIDTH) {{1'b0}}}}, job_in_word_addr, 3'b000}};
    assign bram_in_clk = s_axi_aclk;
    assign bram_in_din = 64'd0;
    assign bram_in_en = job_in_en;
    assign bram_in_rst = !s_axi_aresetn;
    assign bram_in_we = 8'd0;

    assign bram_out_addr = {{{{(29 - OUTPUT_ADDR_WIDTH) {{1'b0}}}}, job_out_word_addr, 3'b000}};
    assign bram_out_clk = s_axi_aclk;
    assign bram_out_din = job_out_din;
    assign bram_out_en = job_out_en;
    assign bram_out_rst = !s_axi_aresetn;
    assign bram_out_we = {{8{{job_out_we}}}};

    dau_identity_registers #(
        .OPERATOR_BITMAP(OPERATOR_BITMAP)
    ) identity_registers (
        .addr({{4'h0, selected_addr[11:0]}}),
        .wen(1'b0),
        .wdata(32'd0),
        .reset_request(reset_request_unused),
        .rdata(identity_rdata)
    );

    dau_bram_stream_job #(
        .INPUT_ADDR_WIDTH(INPUT_ADDR_WIDTH),
        .OUTPUT_ADDR_WIDTH(OUTPUT_ADDR_WIDTH)
    ) job (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(job_start),
        .input_length_bytes(input_length_bytes),
        .busy(job_busy),
        .done(job_done),
        .error(job_error),
        .error_code(job_error_code),
        .result_length_bytes(result_length_bytes),
        .in_addr(job_in_word_addr),
        .in_en(job_in_en),
        .in_dout(bram_in_dout),
        .out_addr(job_out_word_addr),
        .out_en(job_out_en),
        .out_we(job_out_we),
        .out_din(job_out_din),
        .tile_input_valid(tile_input_valid),
        .tile_input_ready(tile_input_ready),
        .tile_input_data(tile_input_data),
        .tile_input_last(tile_input_last),
        .tile_output_valid(tile_output_valid),
        .tile_output_ready(tile_output_ready),
        .tile_output_data(tile_output_data),
        .tile_output_last(tile_output_last),
        .tile_status_valid(tile_status_valid),
        .tile_status_ready(tile_status_ready),
        .tile_status_error(tile_status_error),
        .tile_status_error_code(tile_status_error_code)
    );

    {tile_module} tile (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
{tile_wiring}
    );

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_awready <= 1'b0;
            s_axi_wready <= 1'b0;
            s_axi_bvalid <= 1'b0;
            s_axi_arready <= 1'b0;
            s_axi_rdata <= 32'h0000_0000;
            s_axi_rvalid <= 1'b0;
            input_length_bytes <= 32'd0;
            job_start <= 1'b0;
        end else begin
            job_start <= 1'b0;
            s_axi_awready <= write_fire;
            s_axi_wready <= write_fire;
            s_axi_arready <= read_fire;

            if (write_fire) begin
                s_axi_bvalid <= 1'b1;
                case (s_axi_awaddr[11:0])
                    ADDR_JOB_CONTROL: job_start <= s_axi_wdata[0];
                    ADDR_INPUT_LENGTH_LOW: input_length_bytes <= s_axi_wdata;
                    default: ;  // other job fields accepted and ignored (fixed staging layout)
                endcase
            end else if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid <= 1'b0;
            end

            if (read_fire) begin
                case (s_axi_araddr[11:0])
                    ADDR_JOB_CONTROL: s_axi_rdata <= 32'd0;
                    ADDR_JOB_STATUS: s_axi_rdata <= {{28'd0, job_error, job_done, job_busy, !job_busy}};
                    ADDR_LAST_ERROR: s_axi_rdata <= {{24'd0, job_error_code}};
                    ADDR_INPUT_LENGTH_LOW: s_axi_rdata <= input_length_bytes;
                    ADDR_RESULT_LENGTH_LOW: s_axi_rdata <= result_length_bytes;
                    ADDR_RESULT_LENGTH_HIGH: s_axi_rdata <= 32'd0;
                    default: s_axi_rdata <= identity_rdata;
                endcase
                s_axi_rvalid <= 1'b1;
            end else if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid <= 1'b0;
            end
        end
    end
endmodule

`default_nettype wire
"""


def generate_record_batch_axis_top_sv(
    *,
    module_name: str = "dau_record_batch_axis",
    tile_module: str = "dau_int32_record_batch_aggregation",
) -> str:
    """AXI-Stream shim: adapts a DAU stream tile to XDMA AXI-Stream H2C/C2H
    ports (64-bit), auto-drains status into sticky debug outputs."""
    return f"""`default_nettype none

// GENERATED by dau_build.shell_tops.generate_record_batch_axis_top_sv — do
// not edit. AXI-Stream shim for {tile_module}; plain-Verilog top (BD module
// references require it). tkeep is all-ones out: batches are 64-byte aligned
// and the scalar result stream is a whole number of 64-bit words.
module {module_name} (
    input  wire        aclk,
    input  wire        aresetn,

    input  wire        s_axis_tvalid,
    output wire        s_axis_tready,
    input  wire [63:0] s_axis_tdata,
    input  wire [7:0]  s_axis_tkeep,
    input  wire        s_axis_tlast,

    output wire        m_axis_tvalid,
    input  wire        m_axis_tready,
    output wire [63:0] m_axis_tdata,
    output wire [7:0]  m_axis_tkeep,
    output wire        m_axis_tlast,

    output reg         status_error_sticky,
    output reg  [7:0]  status_error_code_sticky,
    output reg  [31:0] batches_completed
);
    wire       status_valid;
    wire       status_error;
    wire [7:0] status_error_code;

    assign m_axis_tkeep = 8'hff;

    {tile_module} core (
        .clk(aclk),
        .rst(!aresetn),
        .input_valid(s_axis_tvalid),
        .input_ready(s_axis_tready),
        .input_data(s_axis_tdata),
        .input_last(s_axis_tlast),
        .output_valid(m_axis_tvalid),
        .output_ready(m_axis_tready),
        .output_data(m_axis_tdata),
        .output_last(m_axis_tlast),
        .status_valid(status_valid),
        .status_ready(1'b1),
        .status_error(status_error),
        .status_error_code(status_error_code)
    );

    always @(posedge aclk) begin
        if (!aresetn) begin
            status_error_sticky <= 1'b0;
            status_error_code_sticky <= 8'd0;
            batches_completed <= 32'd0;
        end else if (status_valid) begin
            batches_completed <= batches_completed + 32'd1;
            if (status_error) begin
                status_error_sticky <= 1'b1;
                status_error_code_sticky <= status_error_code;
            end
        end
    end

    // s_axis_tkeep is accepted but unused: batches are 64-byte aligned.
    wire unused_tkeep = &s_axis_tkeep;
endmodule

`default_nettype wire
"""


def generate_ohlcv_pipeline_top_sv(
    *,
    module_name: str = "dau_ohlcv_pipeline",
    filter_module: str = "dau_int32_keyed_predicate_filter",
    map_module: str = "dau_int32_keyed_map_alu",
    aggregation_module: str = "dau_int32_grouped_aggregation",
) -> str:
    """Static composed OHLCV pipeline: keyed filter -> keyed map -> ordered
    grouped aggregation over {value, key} pair words. The filter stage gets
    the host-known input row count; downstream stages run last-driven
    (row_count 0 — a compaction upstream makes their counts unknowable at
    config time). Composite status completes when all three stages report,
    or immediately on the first stage error (the pipeline must be reset
    after an error: downstream stages may be mid-stream), or on an
    all-dropped batch (downstream stages never start)."""
    return f"""`default_nettype none

// GENERATED by dau_build.shell_tops.generate_ohlcv_pipeline_top_sv — do not
// edit. Static OHLCV pipeline: {filter_module} -> {map_module} ->
// {aggregation_module} (ordered close-out). Plain-Verilog top (BD module
// references require it). Composite status: success when all three stages
// succeed; first error wins (stage order: filter, map, aggregation) and the
// pipeline must then be reset.
module {module_name} (
    input  wire        clk,
    input  wire        rst,

    input  wire        filter_target_lane,
    input  wire [2:0]  filter_op0,
    input  wire [31:0] filter_constant0,
    input  wire [1:0]  filter_combine,
    input  wire [2:0]  filter_op1,
    input  wire [31:0] filter_constant1,
    input  wire [63:0] row_count,
    input  wire        map_target_lane,
    input  wire [2:0]  map_op,
    input  wire [31:0] map_constant,
    input  wire [4:0]  map_shift,

    input  wire        input_valid,
    output wire        input_ready,
    input  wire [63:0] input_data,
    input  wire        input_last,
    output wire        output_valid,
    input  wire        output_ready,
    output wire [63:0] output_data,
    output wire        output_last,
    output wire        status_valid,
    input  wire        status_ready,
    output wire        status_error,
    output wire [7:0]  status_error_code,
    output wire [63:0] selected_count,
    output wire [63:0] group_count
);
    wire        filter_to_map_valid;
    wire        filter_to_map_ready;
    wire [63:0] filter_to_map_data;
    wire        filter_to_map_last;
    wire        map_to_agg_valid;
    wire        map_to_agg_ready;
    wire [63:0] map_to_agg_data;
    wire        map_to_agg_last;

    wire        filter_status_valid;
    wire        filter_status_error;
    wire [7:0]  filter_status_error_code;
    wire        map_status_valid;
    wire        map_status_error;
    wire [7:0]  map_status_error_code;
    wire        agg_status_valid;
    wire        agg_status_error;
    wire [7:0]  agg_status_error_code;

    {filter_module} filter_stage (
        .clk(clk),
        .rst(rst),
        .cfg_target_lane(filter_target_lane),
        .cfg_op0(filter_op0),
        .cfg_constant0(filter_constant0),
        .cfg_combine(filter_combine),
        .cfg_op1(filter_op1),
        .cfg_constant1(filter_constant1),
        .cfg_row_count(row_count),
        .input_valid(input_valid),
        .input_ready(input_ready),
        .input_data(input_data),
        .input_last(input_last),
        .output_valid(filter_to_map_valid),
        .output_ready(filter_to_map_ready),
        .output_data(filter_to_map_data),
        .output_last(filter_to_map_last),
        .status_valid(filter_status_valid),
        .status_ready(status_fire),
        .status_error(filter_status_error),
        .status_error_code(filter_status_error_code),
        .selected_count(selected_count)
    );

    {map_module} map_stage (
        .clk(clk),
        .rst(rst),
        .cfg_target_lane(map_target_lane),
        .cfg_op(map_op),
        .cfg_constant(map_constant),
        .cfg_shift(map_shift),
        .cfg_row_count(64'd0),  // last-driven: downstream of compaction
        .input_valid(filter_to_map_valid),
        .input_ready(filter_to_map_ready),
        .input_data(filter_to_map_data),
        .input_last(filter_to_map_last),
        .output_valid(map_to_agg_valid),
        .output_ready(map_to_agg_ready),
        .output_data(map_to_agg_data),
        .output_last(map_to_agg_last),
        .status_valid(map_status_valid),
        .status_ready(status_fire),
        .status_error(map_status_error),
        .status_error_code(map_status_error_code)
    );

    {aggregation_module} aggregation_stage (
        .clk(clk),
        .rst(rst),
        .cfg_mode(2'd0),  // ordered close-out
        .cfg_row_count(64'd0),  // last-driven: downstream of compaction
        .input_valid(map_to_agg_valid),
        .input_ready(map_to_agg_ready),
        .input_data(map_to_agg_data),
        .input_last(map_to_agg_last),
        .output_valid(output_valid),
        .output_ready(output_ready),
        .output_data(output_data),
        .output_last(output_last),
        .status_valid(agg_status_valid),
        .status_ready(status_fire),
        .status_error(agg_status_error),
        .status_error_code(agg_status_error_code),
        .group_count(group_count)
    );

    wire any_error = (filter_status_valid && filter_status_error)
        || (map_status_valid && map_status_error)
        || (agg_status_valid && agg_status_error);
    wire all_done = filter_status_valid && map_status_valid && agg_status_valid;
    // an all-dropped batch emits no words, so downstream stages never start
    // (they are still in reset-idle) — the filter's success status closes
    // the whole pipeline
    wire empty_selection_done = filter_status_valid && !filter_status_error && (selected_count == 64'd0);
    wire status_fire = status_valid && status_ready;

    assign status_valid = all_done || any_error || empty_selection_done;
    assign status_error = any_error;
    assign status_error_code = (filter_status_valid && filter_status_error) ? filter_status_error_code
        : (map_status_valid && map_status_error) ? map_status_error_code
        : (agg_status_valid && agg_status_error) ? agg_status_error_code
        : 8'd0;
endmodule

`default_nettype wire
"""


def generate_mm_ohlcv_job_top_sv(
    *,
    module_name: str = "dau_mm_ohlcv_job",
    pipeline_module: str = "dau_ohlcv_pipeline",
    operator_bitmap: int = 0x0000_001E,
    input_addr_width: int = 14,
    output_addr_width: int = 12,
) -> str:
    """MM-shell OHLCV job top: the identity + stream-job register aperture
    extended with the composed-pipeline configuration registers
    (PIPELINE_FILTER_*/PIPELINE_MAP_* — the filter row count derives from
    INPUT_LENGTH, one keyed row per 64-bit word), driving the BRAM-staged
    job runner with the generated OHLCV pipeline as the tile. Group records
    are 40 bytes; the host bounds rows-per-batch so worst-case group output
    fits the output BRAM. On a pipeline error the shell pulses the pipeline
    reset so mid-stream stages recover before the next job."""
    return f"""`default_nettype none

// GENERATED by dau_build.shell_tops.generate_mm_ohlcv_job_top_sv — do not
// edit. Binds {pipeline_module} behind the DAU stream-job register contract
// with BRAM staging and pipeline configuration registers. Plain-Verilog top
// (BD module references require it).
module {module_name} #(
    parameter [31:0] OPERATOR_BITMAP = 32'h{operator_bitmap:08X},
    parameter INPUT_ADDR_WIDTH = {input_addr_width},
    parameter OUTPUT_ADDR_WIDTH = {output_addr_width}
) (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s_axi_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF S_AXI, ASSOCIATED_RESET s_axi_aresetn" *)
    input wire s_axi_aclk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s_axi_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input wire s_axi_aresetn,

    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S_AXI, PROTOCOL AXI4LITE, DATA_WIDTH 32, ADDR_WIDTH 16, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1" *)
    input wire [15:0] s_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWVALID" *)
    input wire s_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI AWREADY" *)
    output reg s_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WDATA" *)
    input wire [31:0] s_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WSTRB" *)
    input wire [3:0] s_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WVALID" *)
    input wire s_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI WREADY" *)
    output reg s_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BRESP" *)
    output wire [1:0] s_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BVALID" *)
    output reg s_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI BREADY" *)
    input wire s_axi_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARADDR" *)
    input wire [15:0] s_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARVALID" *)
    input wire s_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI ARREADY" *)
    output reg s_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RDATA" *)
    output reg [31:0] s_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RRESP" *)
    output wire [1:0] s_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RVALID" *)
    output reg s_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 S_AXI RREADY" *)
    input wire s_axi_rready,

    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN ADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME BRAM_IN, MASTER_TYPE BRAM_CTRL, MEM_WIDTH 64, MEM_SIZE {(1 << input_addr_width) * 8}, READ_WRITE_MODE READ_WRITE" *)
    output wire [31:0] bram_in_addr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN CLK" *)
    output wire bram_in_clk,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN DIN" *)
    output wire [63:0] bram_in_din,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN DOUT" *)
    input wire [63:0] bram_in_dout,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN EN" *)
    output wire bram_in_en,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN RST" *)
    output wire bram_in_rst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_IN WE" *)
    output wire [7:0] bram_in_we,

    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT ADDR" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME BRAM_OUT, MASTER_TYPE BRAM_CTRL, MEM_WIDTH 64, MEM_SIZE {(1 << output_addr_width) * 8}, READ_WRITE_MODE READ_WRITE" *)
    output wire [31:0] bram_out_addr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT CLK" *)
    output wire bram_out_clk,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT DIN" *)
    output wire [63:0] bram_out_din,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT DOUT" *)
    input wire [63:0] bram_out_dout,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT EN" *)
    output wire bram_out_en,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT RST" *)
    output wire bram_out_rst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:bram:1.0 BRAM_OUT WE" *)
    output wire [7:0] bram_out_we
);
    // window-relative decode (the AXI address carries the BAR offset)
    localparam [11:0] ADDR_LAST_ERROR = 12'h{int(RegisterOffset.LAST_ERROR):03X};
    localparam [11:0] ADDR_JOB_CONTROL = 12'h{int(RegisterOffset.JOB_CONTROL):03X};
    localparam [11:0] ADDR_JOB_STATUS = 12'h{int(RegisterOffset.JOB_STATUS):03X};
    localparam [11:0] ADDR_INPUT_LENGTH_LOW = 12'h{int(RegisterOffset.INPUT_LENGTH_LOW):03X};
    localparam [11:0] ADDR_RESULT_LENGTH_LOW = 12'h{int(RegisterOffset.RESULT_LENGTH_LOW):03X};
    localparam [11:0] ADDR_RESULT_LENGTH_HIGH = 12'h{int(RegisterOffset.RESULT_LENGTH_HIGH):03X};
    localparam [11:0] ADDR_PIPELINE_FILTER_OP = 12'h{int(RegisterOffset.PIPELINE_FILTER_OP):03X};
    localparam [11:0] ADDR_PIPELINE_FILTER_CONSTANT0 = 12'h{int(RegisterOffset.PIPELINE_FILTER_CONSTANT0):03X};
    localparam [11:0] ADDR_PIPELINE_FILTER_CONSTANT1 = 12'h{int(RegisterOffset.PIPELINE_FILTER_CONSTANT1):03X};
    localparam [11:0] ADDR_PIPELINE_MAP_OP = 12'h{int(RegisterOffset.PIPELINE_MAP_OP):03X};
    localparam [11:0] ADDR_PIPELINE_MAP_CONSTANT = 12'h{int(RegisterOffset.PIPELINE_MAP_CONSTANT):03X};
    localparam [11:0] ADDR_PIPELINE_SELECTED_COUNT_LOW = 12'h{int(RegisterOffset.PIPELINE_SELECTED_COUNT_LOW):03X};
    localparam [11:0] ADDR_PIPELINE_SELECTED_COUNT_HIGH = 12'h{int(RegisterOffset.PIPELINE_SELECTED_COUNT_HIGH):03X};
    localparam [11:0] ADDR_PIPELINE_GROUP_COUNT_LOW = 12'h{int(RegisterOffset.PIPELINE_GROUP_COUNT_LOW):03X};
    localparam [11:0] ADDR_PIPELINE_GROUP_COUNT_HIGH = 12'h{int(RegisterOffset.PIPELINE_GROUP_COUNT_HIGH):03X};

    wire write_fire;
    wire read_fire;
    wire [15:0] selected_addr;
    wire [31:0] identity_rdata;
    wire [31:0] reset_request_unused;

    reg [31:0] input_length_bytes;
    reg job_start;
    reg [31:0] filter_op_reg;      // [2:0] op0, [5:4] combine, [10:8] op1, [16] target lane
    reg [31:0] filter_constant0;
    reg [31:0] filter_constant1;
    reg [31:0] map_op_reg;         // [2:0] op, [12:8] shift, [16] target lane
    reg [31:0] map_constant;

    wire job_busy;
    wire job_done;
    wire job_error;
    wire [7:0] job_error_code;
    wire [31:0] result_length_bytes;
    wire [INPUT_ADDR_WIDTH-1:0] job_in_word_addr;
    wire [OUTPUT_ADDR_WIDTH-1:0] job_out_word_addr;
    wire job_in_en;
    wire job_out_en;
    wire job_out_we;
    wire [63:0] job_out_din;

    wire tile_input_valid;
    wire tile_input_ready;
    wire [63:0] tile_input_data;
    wire tile_input_last;
    wire tile_output_valid;
    wire tile_output_ready;
    wire [63:0] tile_output_data;
    wire tile_output_last;
    wire tile_status_valid;
    wire tile_status_ready;
    wire tile_status_error;
    wire [7:0] tile_status_error_code;
    wire [63:0] pipeline_selected_count;
    wire [63:0] pipeline_group_count;

    // the pipeline stages clear their counters when the runner consumes
    // their status, so the shell latches the counts for host readback
    reg [63:0] latched_selected_count;
    reg [63:0] latched_group_count;
    // recover mid-stream stages after a pipeline error before the next job
    reg pipeline_error_reset;
    wire pipeline_rst = !s_axi_aresetn || pipeline_error_reset;

    assign write_fire = !s_axi_bvalid && s_axi_awvalid && s_axi_wvalid;
    assign read_fire = !write_fire && !s_axi_rvalid && s_axi_arvalid;
    assign selected_addr = write_fire ? s_axi_awaddr : s_axi_araddr;
    assign s_axi_bresp = 2'b00;
    assign s_axi_rresp = 2'b00;

    // byte addressing toward axi_bram_ctrl-paired block RAM
    assign bram_in_addr = {{{{(29 - INPUT_ADDR_WIDTH) {{1'b0}}}}, job_in_word_addr, 3'b000}};
    assign bram_in_clk = s_axi_aclk;
    assign bram_in_din = 64'd0;
    assign bram_in_en = job_in_en;
    assign bram_in_rst = !s_axi_aresetn;
    assign bram_in_we = 8'd0;

    assign bram_out_addr = {{{{(29 - OUTPUT_ADDR_WIDTH) {{1'b0}}}}, job_out_word_addr, 3'b000}};
    assign bram_out_clk = s_axi_aclk;
    assign bram_out_din = job_out_din;
    assign bram_out_en = job_out_en;
    assign bram_out_rst = !s_axi_aresetn;
    assign bram_out_we = {{8{{job_out_we}}}};

    dau_identity_registers #(
        .OPERATOR_BITMAP(OPERATOR_BITMAP)
    ) identity_registers (
        .addr({{4'h0, selected_addr[11:0]}}),
        .wen(1'b0),
        .wdata(32'd0),
        .reset_request(reset_request_unused),
        .rdata(identity_rdata)
    );

    dau_bram_stream_job #(
        .INPUT_ADDR_WIDTH(INPUT_ADDR_WIDTH),
        .OUTPUT_ADDR_WIDTH(OUTPUT_ADDR_WIDTH),
        .LENGTH_ALIGN_BITS(3)  // 8-byte keyed pair rows, not the 64-byte record-batch grid
    ) job (
        .clk(s_axi_aclk),
        .rst(!s_axi_aresetn),
        .start(job_start),
        .input_length_bytes(input_length_bytes),
        .busy(job_busy),
        .done(job_done),
        .error(job_error),
        .error_code(job_error_code),
        .result_length_bytes(result_length_bytes),
        .in_addr(job_in_word_addr),
        .in_en(job_in_en),
        .in_dout(bram_in_dout),
        .out_addr(job_out_word_addr),
        .out_en(job_out_en),
        .out_we(job_out_we),
        .out_din(job_out_din),
        .tile_input_valid(tile_input_valid),
        .tile_input_ready(tile_input_ready),
        .tile_input_data(tile_input_data),
        .tile_input_last(tile_input_last),
        .tile_output_valid(tile_output_valid),
        .tile_output_ready(tile_output_ready),
        .tile_output_data(tile_output_data),
        .tile_output_last(tile_output_last),
        .tile_status_valid(tile_status_valid),
        .tile_status_ready(tile_status_ready),
        .tile_status_error(tile_status_error),
        .tile_status_error_code(tile_status_error_code)
    );

    {pipeline_module} pipeline (
        .clk(s_axi_aclk),
        .rst(pipeline_rst),
        .filter_target_lane(filter_op_reg[16]),
        .filter_op0(filter_op_reg[2:0]),
        .filter_constant0(filter_constant0),
        .filter_combine(filter_op_reg[5:4]),
        .filter_op1(filter_op_reg[10:8]),
        .filter_constant1(filter_constant1),
        .row_count({{35'd0, input_length_bytes[31:3]}}),
        .map_target_lane(map_op_reg[16]),
        .map_op(map_op_reg[2:0]),
        .map_constant(map_constant),
        .map_shift(map_op_reg[12:8]),
        .input_valid(tile_input_valid),
        .input_ready(tile_input_ready),
        .input_data(tile_input_data),
        .input_last(tile_input_last),
        .output_valid(tile_output_valid),
        .output_ready(tile_output_ready),
        .output_data(tile_output_data),
        .output_last(tile_output_last),
        .status_valid(tile_status_valid),
        .status_ready(tile_status_ready),
        .status_error(tile_status_error),
        .status_error_code(tile_status_error_code),
        .selected_count(pipeline_selected_count),
        .group_count(pipeline_group_count)
    );

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_awready <= 1'b0;
            s_axi_wready <= 1'b0;
            s_axi_bvalid <= 1'b0;
            s_axi_arready <= 1'b0;
            s_axi_rdata <= 32'h0000_0000;
            s_axi_rvalid <= 1'b0;
            input_length_bytes <= 32'd0;
            job_start <= 1'b0;
            filter_op_reg <= 32'd0;
            filter_constant0 <= 32'd0;
            filter_constant1 <= 32'd0;
            map_op_reg <= 32'd0;
            map_constant <= 32'd0;
            latched_selected_count <= 64'd0;
            latched_group_count <= 64'd0;
            pipeline_error_reset <= 1'b0;
        end else begin
            job_start <= 1'b0;
            pipeline_error_reset <= tile_status_valid && tile_status_ready && tile_status_error;
            if (tile_status_valid && tile_status_ready) begin
                latched_selected_count <= pipeline_selected_count;
                latched_group_count <= pipeline_group_count;
            end
            s_axi_awready <= write_fire;
            s_axi_wready <= write_fire;
            s_axi_arready <= read_fire;

            if (write_fire) begin
                s_axi_bvalid <= 1'b1;
                case (s_axi_awaddr[11:0])
                    ADDR_JOB_CONTROL: job_start <= s_axi_wdata[0];
                    ADDR_INPUT_LENGTH_LOW: input_length_bytes <= s_axi_wdata;
                    ADDR_PIPELINE_FILTER_OP: filter_op_reg <= s_axi_wdata;
                    ADDR_PIPELINE_FILTER_CONSTANT0: filter_constant0 <= s_axi_wdata;
                    ADDR_PIPELINE_FILTER_CONSTANT1: filter_constant1 <= s_axi_wdata;
                    ADDR_PIPELINE_MAP_OP: map_op_reg <= s_axi_wdata;
                    ADDR_PIPELINE_MAP_CONSTANT: map_constant <= s_axi_wdata;
                    default: ;  // other job fields accepted and ignored (fixed staging layout)
                endcase
            end else if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid <= 1'b0;
            end

            if (read_fire) begin
                case (s_axi_araddr[11:0])
                    ADDR_JOB_CONTROL: s_axi_rdata <= 32'd0;
                    ADDR_JOB_STATUS: s_axi_rdata <= {{28'd0, job_error, job_done, job_busy, !job_busy}};
                    ADDR_LAST_ERROR: s_axi_rdata <= {{24'd0, job_error_code}};
                    ADDR_INPUT_LENGTH_LOW: s_axi_rdata <= input_length_bytes;
                    ADDR_RESULT_LENGTH_LOW: s_axi_rdata <= result_length_bytes;
                    ADDR_RESULT_LENGTH_HIGH: s_axi_rdata <= 32'd0;
                    ADDR_PIPELINE_FILTER_OP: s_axi_rdata <= filter_op_reg;
                    ADDR_PIPELINE_FILTER_CONSTANT0: s_axi_rdata <= filter_constant0;
                    ADDR_PIPELINE_FILTER_CONSTANT1: s_axi_rdata <= filter_constant1;
                    ADDR_PIPELINE_MAP_OP: s_axi_rdata <= map_op_reg;
                    ADDR_PIPELINE_MAP_CONSTANT: s_axi_rdata <= map_constant;
                    ADDR_PIPELINE_SELECTED_COUNT_LOW: s_axi_rdata <= latched_selected_count[31:0];
                    ADDR_PIPELINE_SELECTED_COUNT_HIGH: s_axi_rdata <= latched_selected_count[63:32];
                    ADDR_PIPELINE_GROUP_COUNT_LOW: s_axi_rdata <= latched_group_count[31:0];
                    ADDR_PIPELINE_GROUP_COUNT_HIGH: s_axi_rdata <= latched_group_count[63:32];
                    default: s_axi_rdata <= identity_rdata;
                endcase
                s_axi_rvalid <= 1'b1;
            end else if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid <= 1'b0;
            end
        end
    end
endmodule

`default_nettype wire
"""
