# GENERATED by dau_build.mm_shell — do not edit.
# Example board pin constraints. GT channel LOCs (the lane swizzle) are
# applied by the pre-opt_design implementation hook, never here: XDC-time
# LOCs conflict with the XDMA IP's internal BEL/LOC constraints.

set_property PACKAGE_PIN F6 [get_ports {pcie_clkin_clk_p[0]}]
set_property PACKAGE_PIN E6 [get_ports {pcie_clkin_clk_n[0]}]

set_property PACKAGE_PIN J1 [get_ports pci_reset]
set_property IOSTANDARD LVCMOS33 [get_ports pci_reset]
set_false_path -from [get_ports pci_reset]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property IOSTANDARD LVDS_25 [get_ports sys_clk_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_clk_n]

set_property PACKAGE_PIN H4 [get_ports LED_A4]
set_property IOSTANDARD LVCMOS33 [get_ports LED_A4]
