# GENERATED by dau_build.mm_shell — do not edit.
# Pre-opt_design implementation hook: apply the board's PCIe lane swizzle
# after the IP's own XDC constraints, per CRITICAL WARNING 18-4427 guidance.
set swizzle {7 GTXE2_CHANNEL_X0Y7 6 GTXE2_CHANNEL_X0Y6 5 GTXE2_CHANNEL_X0Y5 4 GTXE2_CHANNEL_X0Y4 3 GTXE2_CHANNEL_X0Y3 2 GTXE2_CHANNEL_X0Y2 1 GTXE2_CHANNEL_X0Y1 0 GTXE2_CHANNEL_X0Y0}
set lane_cells [dict create]
set gts [get_cells -hierarchical -quiet -filter {REF_NAME == GTXE2_CHANNEL || ORIG_REF_NAME == GTXE2_CHANNEL}]
foreach cell $gts {
    if {[regexp {pipe_lane\[(\d+)\]} $cell -> lane]} {
        dict set lane_cells $lane $cell
    }
}
if {[dict size $lane_cells] != 8} {
    error "gt_lane_swizzle: expected 8 GTXE2_CHANNEL lane cells, found [dict size $lane_cells]"
}
# two-phase: release every lane's LOC first, then place — interleaved
# reset/set hits "bel is occupied" when a target site is still held by a
# not-yet-processed lane (Vivado 12-2285, a CRITICAL WARNING that silently
# leaves lanes crossed)
foreach {lane channel} $swizzle {
    reset_property -quiet LOC [dict get $lane_cells $lane]
}
foreach {lane channel} $swizzle {
    set cell [dict get $lane_cells $lane]
    set_property LOC $channel $cell
    set got [get_property LOC $cell]
    if {$got ne $channel} {
        error "gt_lane_swizzle: pipe_lane\[$lane\] LOC is '$got', wanted $channel"
    }
    puts "gt_lane_swizzle: pipe_lane\[$lane\] ($cell) -> $channel"
}
