# GENERATED by dau_build.dpv1_shell — do not edit.
# DAU MM DDR job shell: XDMA (memory-mapped, proven DAU platform variant 1
# (dpv1) PCIe personality) with DDR staging behind the memory controller.
set origin_dir [file dirname [file normalize [info script]]]

create_project -force project_mm "$origin_dir/project_mm" -part xc7a200tfbg484-2

add_files [list \
    "/src/tile.sv" \
    "/work/shell/my_ddr_top.v" \
]
set_property file_type SystemVerilog [get_files "/src/tile.sv"]

add_files -fileset constrs_1 "$origin_dir/constraints.xdc"
set_property PROCESSING_ORDER EARLY [get_files "$origin_dir/constraints.xdc"]

create_bd_design Top

set xdma_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:xdma xdma_0]
set_property -dict [list \
    CONFIG.mode_selection {Advanced} \
    CONFIG.pl_link_cap_max_link_width {X4} \
    CONFIG.pl_link_cap_max_link_speed {5.0_GT/s} \
    CONFIG.axi_data_width {128_bit} \
    CONFIG.axisten_freq {125} \
    CONFIG.xdma_axi_intf_mm {AXI_Memory_Mapped} \
    CONFIG.xdma_rnum_chnl {1} \
    CONFIG.xdma_wnum_chnl {1} \
    CONFIG.xdma_sts_ports {false} \
    CONFIG.axilite_master_en {true} \
    CONFIG.axilite_master_size {128} \
    CONFIG.axilite_master_scale {Kilobytes} \
    CONFIG.axil_master_64bit_en {true} \
    CONFIG.axil_master_prefetchable {true} \
    CONFIG.xdma_pcie_64bit_en {true} \
    CONFIG.xdma_pcie_prefetchable {true} \
    CONFIG.plltype {QPLL1} \
    CONFIG.cfg_mgmt_if {false} \
    CONFIG.copy_pf0 {true} \
    CONFIG.runbit_fix {false} \
    CONFIG.en_ext_ch_gt_drp {false} \
    CONFIG.en_pcie_drp {false} \
    CONFIG.en_transceiver_status_ports {false} \
    CONFIG.enable_gen4 {false} \
    CONFIG.vendor_id {10EE} \
    CONFIG.pf0_device_id {7011} \
    CONFIG.pf0_Use_Class_Code_Lookup_Assistant {false} \
    CONFIG.pf0_base_class_menu {Device_was_built_before_Class_Code_definitions_were_finalized} \
    CONFIG.pf0_sub_class_interface_menu {All_currently_implemented_devices_except_VGA-compatible_devices} \
    CONFIG.pf0_class_code {120000} \
    CONFIG.pf0_class_code_base {12} \
    CONFIG.pf0_class_code_sub {00} \
    CONFIG.pf0_class_code_interface {00} \
    CONFIG.pf0_subsystem_vendor_id {0} \
    CONFIG.pf0_subsystem_id {0} \
    CONFIG.pf0_msix_cap_table_bir {BAR_3:2} \
    CONFIG.pf0_msix_cap_pba_bir {BAR_3:2} \
    CONFIG.pf1_msix_cap_table_size {000} \
    CONFIG.pf1_msix_cap_table_offset {00000000} \
    CONFIG.pf1_msix_cap_pba_offset {00000000} \
    CONFIG.PF0_DEVICE_ID_mqdma {9024} \
    CONFIG.PF2_DEVICE_ID_mqdma {9024} \
    CONFIG.PF3_DEVICE_ID_mqdma {9024} \
    CONFIG.PF0_SRIOV_VF_DEVICE_ID {0000} \
    CONFIG.PF1_SRIOV_VF_DEVICE_ID {A134} \
    CONFIG.PF2_SRIOV_VF_DEVICE_ID {A234} \
    CONFIG.PF3_SRIOV_VF_DEVICE_ID {A334} \
] $xdma_0

set refclk_buf [create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf refclk_buf]
set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} $refclk_buf
set clkreq_low [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant clkreq_low]
set_property -dict [list CONFIG.CONST_VAL {0} CONFIG.CONST_WIDTH {1}] $clkreq_low

make_bd_intf_pins_external [get_bd_intf_pins xdma_0/pcie_mgt]
set_property name pcie_mgt [get_bd_intf_ports pcie_mgt_0]
set pcie_clkin [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 pcie_clkin]
set_property CONFIG.FREQ_HZ {100000000} $pcie_clkin
connect_bd_intf_net $pcie_clkin [get_bd_intf_pins refclk_buf/CLK_IN_D]
set pci_reset [create_bd_port -dir I -type rst pci_reset]
set_property CONFIG.POLARITY {ACTIVE_LOW} $pci_reset
connect_bd_net $pci_reset [get_bd_pins xdma_0/sys_rst_n]
set clkreq_port [create_bd_port -dir O -from 0 -to 0 pcie_clkreq_l]
connect_bd_net [get_bd_pins clkreq_low/dout] $clkreq_port
set led_port [create_bd_port -dir O -from 0 -to 0 LED_M2]
connect_bd_net [get_bd_pins xdma_0/user_lnk_up] $led_port
connect_bd_net [get_bd_pins refclk_buf/IBUF_OUT] [get_bd_pins xdma_0/sys_clk]

set dau_job [create_bd_cell -type module -reference my_ddr_top my_ddr_top_0]

# memory controller from the vendored proven configuration; the .prj owns
# the DDR3 and sys_clk pin placement
set mig_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:mig_7series mig_0]
set_property -dict [list \
    CONFIG.XML_INPUT_FILE "$origin_dir/dpv1_mig.prj" \
    CONFIG.RESET_BOARD_INTERFACE {Custom} \
    CONFIG.MIG_DONT_TOUCH_PARAM {Custom} \
    CONFIG.BOARD_MIG_PARAM {Custom} \
] $mig_0

set sys_clk [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 sys_clk]
set_property CONFIG.FREQ_HZ {200000000} $sys_clk
connect_bd_intf_net $sys_clk [get_bd_intf_pins mig_0/SYS_CLK]
make_bd_intf_pins_external [get_bd_intf_pins mig_0/DDR3]
set_property name DDR3 [get_bd_intf_ports DDR3_0]

set mig_high [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant mig_high]
set_property -dict [list CONFIG.CONST_VAL {1} CONFIG.CONST_WIDTH {1}] $mig_high
connect_bd_net [get_bd_pins mig_high/dout] [get_bd_pins mig_0/sys_rst] [get_bd_pins mig_0/aresetn]
set calib_led_port [create_bd_port -dir O LED_A4]
connect_bd_net [get_bd_pins mig_0/init_calib_complete] $calib_led_port

set xadc_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:xadc_wiz xadc_0]
set_property -dict [list \
    CONFIG.INTERFACE_SELECTION {Enable_AXI} \
    CONFIG.ENABLE_TEMP_BUS {true} \
    CONFIG.DCLK_FREQUENCY {125} \
    CONFIG.ADC_CONVERSION_RATE {1000} \
    CONFIG.ENABLE_RESET {false} \
] $xadc_0
connect_bd_net [get_bd_pins xadc_0/temp_out] [get_bd_pins mig_0/device_temp_i]

# one memory-side smartconnect: XDMA (128-bit) and the job master (64-bit)
# into the controller's 128-bit S_AXI, bridging 125 MHz -> ui_clk
set smc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smc]
set_property -dict [list CONFIG.NUM_SI {2} CONFIG.NUM_MI {1} CONFIG.NUM_CLKS {2}] $smc
connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI] [get_bd_intf_pins smc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins my_ddr_top_0/M_AXI] [get_bd_intf_pins smc/S01_AXI]
connect_bd_intf_net [get_bd_intf_pins smc/M00_AXI] [get_bd_intf_pins mig_0/S_AXI]

# the proven shell routes M_AXI_LITE through an interconnect, never directly
# into a register block; smc_lite mirrors that (pipelined, spec-strict
# handshakes between the XDMA AXI-Lite master and the module reference)
set smc_lite [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smc_lite]
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {2}] $smc_lite
connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI_LITE] [get_bd_intf_pins smc_lite/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins smc_lite/M00_AXI] [get_bd_intf_pins my_ddr_top_0/S_AXI]
connect_bd_intf_net [get_bd_intf_pins smc_lite/M01_AXI] [get_bd_intf_pins xadc_0/s_axi_lite]

connect_bd_net [get_bd_pins xdma_0/axi_aclk] \
    [get_bd_pins smc/aclk] [get_bd_pins smc_lite/aclk] [get_bd_pins xadc_0/s_axi_aclk] \
    [get_bd_pins my_ddr_top_0/s_axi_aclk]
connect_bd_net [get_bd_pins mig_0/ui_clk] [get_bd_pins smc/aclk1]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] \
    [get_bd_pins smc/aresetn] [get_bd_pins smc_lite/aresetn] [get_bd_pins xadc_0/s_axi_aresetn] \
    [get_bd_pins my_ddr_top_0/s_axi_aresetn]

assign_bd_address -offset 0x00000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs mig_0/memmap/memaddr] -force
assign_bd_address -offset 0x00000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces my_ddr_top_0/M_AXI] [get_bd_addr_segs mig_0/memmap/memaddr] -force
assign_bd_address -offset 0x00001000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs my_ddr_top_0/S_AXI/*] -force
assign_bd_address -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs xadc_0/s_axi_lite/*] -force

validate_bd_design
save_bd_design

make_wrapper -files [get_files [get_property FILE_NAME [get_bd_designs Top]]] -top
add_files -norecurse "$origin_dir/project_mm/project_mm.gen/sources_1/bd/Top/hdl/Top_wrapper.v"
set_property top Top_wrapper [current_fileset]
update_compile_order -fileset sources_1

launch_runs synth_1 -jobs 12
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "DAU_MM_JOB_BUILD_FAILED synthesis"
    exit 1
}

set_property STEPS.OPT_DESIGN.TCL.PRE "$origin_dir/gt_lane_swizzle.tcl" [get_runs impl_1]
launch_runs impl_1 -to_step write_bitstream -jobs 12
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "DAU_MM_JOB_BUILD_FAILED implementation"
    exit 1
}
open_run impl_1
report_utilization -file "$origin_dir/utilization_mm.rpt"
report_timing_summary -file "$origin_dir/timing_mm.rpt"

set routed_lanes [dict create]
foreach cell [get_cells -hierarchical -quiet -filter {REF_NAME == GTPE2_CHANNEL || ORIG_REF_NAME == GTPE2_CHANNEL}] {
    if {[regexp {pipe_lane\[(\d+)\]} $cell -> lane]} {
        dict set routed_lanes $lane [get_property LOC $cell]
    }
}
foreach {lane channel} {3 GTPE2_CHANNEL_X0Y7 0 GTPE2_CHANNEL_X0Y6 2 GTPE2_CHANNEL_X0Y5 1 GTPE2_CHANNEL_X0Y4} {
    if {![dict exists $routed_lanes $lane] || [dict get $routed_lanes $lane] != $channel} {
        puts "DAU_MM_JOB_BUILD_FAILED lane $lane misplaced (expected $channel)"
        exit 1
    }
}
puts "lane swizzle verified"

set wns [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1 -setup]]
file copy -force "$origin_dir/project_mm/project_mm.runs/impl_1/Top_wrapper.bit" "$origin_dir/dau_mm_job.bit"
puts "DAU_MM_JOB_BUILD_OK wns=$wns"
exit 0
