# GENERATED by dau_build.dpv1_shell — do not edit.
# DAU MM job shell: XDMA (memory-mapped, proven DAU platform variant 1 (dpv1) PCIe personality)
# with BRAM staging at the stream-job contract addresses.
set origin_dir [file dirname [file normalize [info script]]]

create_project -force project_mm "$origin_dir/project_mm" -part xc7a200tfbg484-2

add_files [list \
    "/src/tile.sv" \
    "/src/identity.v" \
    "/work/shell/my_top.v" \
]
set_property file_type SystemVerilog [get_files "/src/tile.sv"]

add_files -fileset constrs_1 "$origin_dir/constraints.xdc"
set_property PROCESSING_ORDER EARLY [get_files "$origin_dir/constraints.xdc"]

create_bd_design Top

set xdma_0 [create_bd_cell -type ip -vlnv xilinx.com:ip:xdma xdma_0]
set_property -dict [list \
    CONFIG.mode_selection {Advanced} \
    CONFIG.pl_link_cap_max_link_width {X4} \
    CONFIG.pl_link_cap_max_link_speed {5.0_GT/s} \
    CONFIG.axi_data_width {128_bit} \
    CONFIG.axisten_freq {125} \
    CONFIG.xdma_axi_intf_mm {AXI_Memory_Mapped} \
    CONFIG.xdma_rnum_chnl {1} \
    CONFIG.xdma_wnum_chnl {1} \
    CONFIG.xdma_sts_ports {false} \
    CONFIG.axilite_master_en {true} \
    CONFIG.axilite_master_size {128} \
    CONFIG.axilite_master_scale {Kilobytes} \
    CONFIG.axil_master_64bit_en {true} \
    CONFIG.axil_master_prefetchable {true} \
    CONFIG.xdma_pcie_64bit_en {true} \
    CONFIG.xdma_pcie_prefetchable {true} \
    CONFIG.plltype {QPLL1} \
    CONFIG.cfg_mgmt_if {false} \
    CONFIG.copy_pf0 {true} \
    CONFIG.runbit_fix {false} \
    CONFIG.en_ext_ch_gt_drp {false} \
    CONFIG.en_pcie_drp {false} \
    CONFIG.en_transceiver_status_ports {false} \
    CONFIG.enable_gen4 {false} \
    CONFIG.vendor_id {10EE} \
    CONFIG.pf0_device_id {7011} \
    CONFIG.pf0_Use_Class_Code_Lookup_Assistant {false} \
    CONFIG.pf0_base_class_menu {Device_was_built_before_Class_Code_definitions_were_finalized} \
    CONFIG.pf0_sub_class_interface_menu {All_currently_implemented_devices_except_VGA-compatible_devices} \
    CONFIG.pf0_class_code {120000} \
    CONFIG.pf0_class_code_base {12} \
    CONFIG.pf0_class_code_sub {00} \
    CONFIG.pf0_class_code_interface {00} \
    CONFIG.pf0_subsystem_vendor_id {0} \
    CONFIG.pf0_subsystem_id {0} \
    CONFIG.pf0_msix_cap_table_bir {BAR_3:2} \
    CONFIG.pf0_msix_cap_pba_bir {BAR_3:2} \
    CONFIG.pf1_msix_cap_table_size {000} \
    CONFIG.pf1_msix_cap_table_offset {00000000} \
    CONFIG.pf1_msix_cap_pba_offset {00000000} \
    CONFIG.PF0_DEVICE_ID_mqdma {9024} \
    CONFIG.PF2_DEVICE_ID_mqdma {9024} \
    CONFIG.PF3_DEVICE_ID_mqdma {9024} \
    CONFIG.PF0_SRIOV_VF_DEVICE_ID {0000} \
    CONFIG.PF1_SRIOV_VF_DEVICE_ID {A134} \
    CONFIG.PF2_SRIOV_VF_DEVICE_ID {A234} \
    CONFIG.PF3_SRIOV_VF_DEVICE_ID {A334} \
] $xdma_0

set refclk_buf [create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf refclk_buf]
set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} $refclk_buf
set clkreq_low [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant clkreq_low]
set_property -dict [list CONFIG.CONST_VAL {0} CONFIG.CONST_WIDTH {1}] $clkreq_low

make_bd_intf_pins_external [get_bd_intf_pins xdma_0/pcie_mgt]
set_property name pcie_mgt [get_bd_intf_ports pcie_mgt_0]
set pcie_clkin [create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 pcie_clkin]
set_property CONFIG.FREQ_HZ {100000000} $pcie_clkin
connect_bd_intf_net $pcie_clkin [get_bd_intf_pins refclk_buf/CLK_IN_D]
set pci_reset [create_bd_port -dir I -type rst pci_reset]
set_property CONFIG.POLARITY {ACTIVE_LOW} $pci_reset
connect_bd_net $pci_reset [get_bd_pins xdma_0/sys_rst_n]
set clkreq_port [create_bd_port -dir O -from 0 -to 0 pcie_clkreq_l]
connect_bd_net [get_bd_pins clkreq_low/dout] $clkreq_port
set led_port [create_bd_port -dir O -from 0 -to 0 LED_M2]
connect_bd_net [get_bd_pins xdma_0/user_lnk_up] $led_port
connect_bd_net [get_bd_pins refclk_buf/IBUF_OUT] [get_bd_pins xdma_0/sys_clk]

set dau_job [create_bd_cell -type module -reference my_top my_top_0]

set bram_ctrl_in [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl bram_ctrl_in]
set_property -dict [list CONFIG.DATA_WIDTH {64} CONFIG.SINGLE_PORT_BRAM {1}] $bram_ctrl_in
set bram_ctrl_out [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl bram_ctrl_out]
set_property -dict [list CONFIG.DATA_WIDTH {64} CONFIG.SINGLE_PORT_BRAM {1}] $bram_ctrl_out
set mem_in [create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen mem_in]
set_property -dict [list CONFIG.Memory_Type {True_Dual_Port_RAM} CONFIG.use_bram_block {BRAM_Controller} CONFIG.Enable_B {Use_ENB_Pin}] $mem_in
set mem_out [create_bd_cell -type ip -vlnv xilinx.com:ip:blk_mem_gen mem_out]
set_property -dict [list CONFIG.Memory_Type {True_Dual_Port_RAM} CONFIG.use_bram_block {BRAM_Controller} CONFIG.Enable_B {Use_ENB_Pin}] $mem_out

connect_bd_intf_net [get_bd_intf_pins bram_ctrl_in/BRAM_PORTA] [get_bd_intf_pins mem_in/BRAM_PORTA]
connect_bd_intf_net [get_bd_intf_pins my_top_0/BRAM_IN] [get_bd_intf_pins mem_in/BRAM_PORTB]
connect_bd_intf_net [get_bd_intf_pins bram_ctrl_out/BRAM_PORTA] [get_bd_intf_pins mem_out/BRAM_PORTA]
connect_bd_intf_net [get_bd_intf_pins my_top_0/BRAM_OUT] [get_bd_intf_pins mem_out/BRAM_PORTB]

set smc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smc]
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {2}] $smc
set dw_in [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dwidth_converter dw_in]
set_property -dict [list CONFIG.SI_DATA_WIDTH {128} CONFIG.MI_DATA_WIDTH {64}] $dw_in
set dw_out [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dwidth_converter dw_out]
set_property -dict [list CONFIG.SI_DATA_WIDTH {128} CONFIG.MI_DATA_WIDTH {64}] $dw_out
connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI] [get_bd_intf_pins smc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins smc/M00_AXI] [get_bd_intf_pins dw_in/S_AXI]
connect_bd_intf_net [get_bd_intf_pins dw_in/M_AXI] [get_bd_intf_pins bram_ctrl_in/S_AXI]
connect_bd_intf_net [get_bd_intf_pins smc/M01_AXI] [get_bd_intf_pins dw_out/S_AXI]
connect_bd_intf_net [get_bd_intf_pins dw_out/M_AXI] [get_bd_intf_pins bram_ctrl_out/S_AXI]

# the proven shell routes M_AXI_LITE through an interconnect, never directly
# into a register block; smc_lite mirrors that (pipelined, spec-strict
# handshakes between the XDMA AXI-Lite master and the module reference)
set smc_lite [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smc_lite]
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {1}] $smc_lite
connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI_LITE] [get_bd_intf_pins smc_lite/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins smc_lite/M00_AXI] [get_bd_intf_pins my_top_0/S_AXI]

connect_bd_net [get_bd_pins xdma_0/axi_aclk] \
    [get_bd_pins smc/aclk] [get_bd_pins smc_lite/aclk] [get_bd_pins bram_ctrl_in/s_axi_aclk] [get_bd_pins bram_ctrl_out/s_axi_aclk] \
    [get_bd_pins dw_in/s_axi_aclk] [get_bd_pins dw_out/s_axi_aclk] \
    [get_bd_pins my_top_0/s_axi_aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] \
    [get_bd_pins smc/aresetn] [get_bd_pins smc_lite/aresetn] [get_bd_pins bram_ctrl_in/s_axi_aresetn] [get_bd_pins bram_ctrl_out/s_axi_aresetn] \
    [get_bd_pins dw_in/s_axi_aresetn] [get_bd_pins dw_out/s_axi_aresetn] \
    [get_bd_pins my_top_0/s_axi_aresetn]

assign_bd_address -offset 0x00000000 -range 0x00020000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs bram_ctrl_in/S_AXI/*] -force
assign_bd_address -offset 0x00100000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs bram_ctrl_out/S_AXI/*] -force
assign_bd_address -offset 0x00001000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs my_top_0/S_AXI/*] -force

validate_bd_design
save_bd_design

make_wrapper -files [get_files [get_property FILE_NAME [get_bd_designs Top]]] -top
add_files -norecurse "$origin_dir/project_mm/project_mm.gen/sources_1/bd/Top/hdl/Top_wrapper.v"
set_property top Top_wrapper [current_fileset]
update_compile_order -fileset sources_1

launch_runs synth_1 -jobs 12
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "DAU_MM_JOB_BUILD_FAILED synthesis"
    exit 1
}

set_property STEPS.OPT_DESIGN.TCL.PRE "$origin_dir/gt_lane_swizzle.tcl" [get_runs impl_1]
launch_runs impl_1 -to_step write_bitstream -jobs 12
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "DAU_MM_JOB_BUILD_FAILED implementation"
    exit 1
}
open_run impl_1
report_utilization -file "$origin_dir/utilization_mm.rpt"
report_timing_summary -file "$origin_dir/timing_mm.rpt"

set routed_lanes [dict create]
foreach cell [get_cells -hierarchical -quiet -filter {REF_NAME == GTPE2_CHANNEL || ORIG_REF_NAME == GTPE2_CHANNEL}] {
    if {[regexp {pipe_lane\[(\d+)\]} $cell -> lane]} {
        dict set routed_lanes $lane [get_property LOC $cell]
    }
}
foreach {lane channel} {3 GTPE2_CHANNEL_X0Y7 0 GTPE2_CHANNEL_X0Y6 2 GTPE2_CHANNEL_X0Y5 1 GTPE2_CHANNEL_X0Y4} {
    if {![dict exists $routed_lanes $lane] || [dict get $routed_lanes $lane] != $channel} {
        puts "DAU_MM_JOB_BUILD_FAILED lane $lane misplaced (expected $channel)"
        exit 1
    }
}
puts "lane swizzle verified"

set wns [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1 -setup]]
file copy -force "$origin_dir/project_mm/project_mm.runs/impl_1/Top_wrapper.bit" "$origin_dir/dau_mm_job.bit"
puts "DAU_MM_JOB_BUILD_OK wns=$wns"
exit 0
