from __future__ import annotations

from pathlib import Path
from shutil import which

import pytest
from dau_core.hdl import (
    DAU_AGGREGATION_PKG_SV,
    DAU_BRAM_STREAM_JOB_SV,
    DAU_IDENTITY_REGISTERS_SV,
    DAU_INT32_GROUPED_AGGREGATION_SV,
    DAU_INT32_KEYED_MAP_ALU_SV,
    DAU_INT32_KEYED_PREDICATE_FILTER_SV,
    DAU_INT32_RECORD_BATCH_AGGREGATION_SV,
    DAU_MAP_ALU_PKG_SV,
    DAU_PREDICATE_PKG_SV,
)
from dau_core.registers import RegisterOffset

from dau_build.shell_tops import (
    generate_mm_ohlcv_job_top_sv,
    generate_mm_stream_job_top_sv,
    generate_ohlcv_pipeline_top_sv,
    generate_record_batch_axis_top_sv,
)

_SV_TB_DIR = Path(__file__).parent / "sv"
_BENCH_PREFIX = "dau_build.tests.cocotb_benches"


def test_mm_job_top_embeds_register_contract_offsets() -> None:
    text = generate_mm_stream_job_top_sv()
    assert f"12'h{int(RegisterOffset.JOB_CONTROL):03X}" in text
    assert f"12'h{int(RegisterOffset.JOB_STATUS):03X}" in text
    assert f"12'h{int(RegisterOffset.INPUT_LENGTH_LOW):03X}" in text
    assert f"12'h{int(RegisterOffset.RESULT_LENGTH_LOW):03X}" in text
    assert "module dau_mm_stream_job" in text
    assert "dau_int32_record_batch_aggregation tile" in text
    assert "dau_bram_stream_job" in text
    assert "GENERATED by dau_build.shell_tops" in text


def test_mm_job_top_is_parameterizable() -> None:
    text = generate_mm_stream_job_top_sv(module_name="custom_top", tile_module="my_tile", operator_bitmap=0x2)
    assert "module custom_top" in text
    assert "my_tile tile" in text
    assert "32'h00000002" in text


def test_axis_top_wraps_selected_tile() -> None:
    text = generate_record_batch_axis_top_sv(tile_module="my_tile")
    assert "my_tile core" in text
    assert "s_axis_tvalid" in text and "m_axis_tkeep" in text


@pytest.mark.skipif(which("verilator") is None, reason="verilator not found")
def test_generated_mm_job_top_passes_composed_cocotb_bench(tmp_path: Path) -> None:
    generated = tmp_path / "dau_mm_stream_job.v"
    generated.write_text(generate_mm_stream_job_top_sv())
    _run_cocotb_verilator(
        sources=(
            Path(str(DAU_AGGREGATION_PKG_SV)),
            Path(str(DAU_INT32_RECORD_BATCH_AGGREGATION_SV)),
            Path(str(DAU_BRAM_STREAM_JOB_SV)),
            Path(str(DAU_IDENTITY_REGISTERS_SV)),
            generated,
            _SV_TB_DIR / "dau_mm_stream_job_sim.sv",
        ),
        hdl_toplevel="dau_mm_stream_job_sim",
        test_module=f"{_BENCH_PREFIX}.dau_mm_stream_job_tb",
        tmp_path=tmp_path,
    )


@pytest.mark.skipif(which("verilator") is None, reason="verilator not found")
def test_generated_axis_top_passes_cocotb_bench(tmp_path: Path) -> None:
    generated = tmp_path / "dau_record_batch_axis.v"
    generated.write_text(generate_record_batch_axis_top_sv())
    _run_cocotb_verilator(
        sources=(
            Path(str(DAU_AGGREGATION_PKG_SV)),
            Path(str(DAU_INT32_RECORD_BATCH_AGGREGATION_SV)),
            generated,
        ),
        hdl_toplevel="dau_record_batch_axis",
        test_module=f"{_BENCH_PREFIX}.dau_record_batch_axis_tb",
        tmp_path=tmp_path,
    )


def _run_cocotb_verilator(*, sources: tuple[Path, ...], hdl_toplevel: str, test_module: str, tmp_path: Path) -> None:
    runner_module = pytest.importorskip("cocotb_tools.runner", reason="cocotb runner not installed")
    runner = runner_module.get_runner("verilator")
    build_dir = tmp_path / hdl_toplevel
    runner.build(
        sources=sources,
        hdl_toplevel=hdl_toplevel,
        build_dir=build_dir,
        always=True,
        build_args=("--timing", "-Wno-fatal"),
    )
    runner.test(
        hdl_toplevel=hdl_toplevel,
        test_module=test_module,
        build_dir=build_dir,
        results_xml=str(tmp_path / f"{hdl_toplevel}-cocotb-results.xml"),
    )


def test_ohlcv_pipeline_top_chains_the_three_stages() -> None:
    text = generate_ohlcv_pipeline_top_sv()
    assert "module dau_ohlcv_pipeline" in text
    assert "dau_int32_keyed_predicate_filter filter_stage" in text
    assert "dau_int32_keyed_map_alu map_stage" in text
    assert "dau_int32_grouped_aggregation aggregation_stage" in text
    # downstream-of-compaction stages run last-driven
    assert text.count("cfg_row_count(64'd0)") == 2
    assert "GENERATED by dau_build.shell_tops" in text


@pytest.mark.skipif(which("verilator") is None, reason="verilator not found")
def test_generated_ohlcv_pipeline_passes_composed_cocotb_bench(tmp_path: Path) -> None:
    generated = tmp_path / "dau_ohlcv_pipeline.v"
    generated.write_text(generate_ohlcv_pipeline_top_sv())
    _run_cocotb_verilator(
        sources=(
            Path(str(DAU_PREDICATE_PKG_SV)),
            Path(str(DAU_MAP_ALU_PKG_SV)),
            Path(str(DAU_INT32_KEYED_PREDICATE_FILTER_SV)),
            Path(str(DAU_INT32_KEYED_MAP_ALU_SV)),
            Path(str(DAU_INT32_GROUPED_AGGREGATION_SV)),
            generated,
        ),
        hdl_toplevel="dau_ohlcv_pipeline",
        test_module=f"{_BENCH_PREFIX}.dau_ohlcv_pipeline_tb",
        tmp_path=tmp_path,
    )


def test_mm_ohlcv_job_top_embeds_pipeline_register_offsets() -> None:
    text = generate_mm_ohlcv_job_top_sv()
    assert "module dau_mm_ohlcv_job" in text
    assert f"12'h{int(RegisterOffset.PIPELINE_FILTER_OP):03X}" in text
    assert f"12'h{int(RegisterOffset.PIPELINE_MAP_CONSTANT):03X}" in text
    assert f"12'h{int(RegisterOffset.PIPELINE_GROUP_COUNT_LOW):03X}" in text
    # filter row count derives from INPUT_LENGTH, one row per 64-bit word
    assert "input_length_bytes[31:3]" in text
    assert "dau_ohlcv_pipeline pipeline" in text
    assert "dau_bram_stream_job" in text


@pytest.mark.skipif(which("verilator") is None, reason="verilator not found")
def test_generated_mm_ohlcv_job_passes_composed_cocotb_bench(tmp_path: Path) -> None:
    pipeline = tmp_path / "dau_ohlcv_pipeline.v"
    pipeline.write_text(generate_ohlcv_pipeline_top_sv())
    generated = tmp_path / "dau_mm_ohlcv_job.v"
    generated.write_text(generate_mm_ohlcv_job_top_sv())
    _run_cocotb_verilator(
        sources=(
            Path(str(DAU_PREDICATE_PKG_SV)),
            Path(str(DAU_MAP_ALU_PKG_SV)),
            Path(str(DAU_INT32_KEYED_PREDICATE_FILTER_SV)),
            Path(str(DAU_INT32_KEYED_MAP_ALU_SV)),
            Path(str(DAU_INT32_GROUPED_AGGREGATION_SV)),
            Path(str(DAU_BRAM_STREAM_JOB_SV)),
            Path(str(DAU_IDENTITY_REGISTERS_SV)),
            pipeline,
            generated,
            _SV_TB_DIR / "dau_mm_ohlcv_job_sim.sv",
        ),
        hdl_toplevel="dau_mm_ohlcv_job_sim",
        test_module=f"{_BENCH_PREFIX}.dau_mm_ohlcv_job_tb",
        tmp_path=tmp_path,
    )
