from __future__ import annotations

from pathlib import Path

import pytest
from pydantic import ValidationError

from dau_build.scan_composition import (
    LaneTile,
    RegisterLayout,
    ScanComposition,
    ScanCompositionError,
    TileInstance,
    generate_scan_composition_sim_sv,
    generate_scan_composition_top_sv,
)

_FIXTURES = Path(__file__).parent / "fixtures" / "scan_composition"


def _bar_noc_composition() -> ScanComposition:
    """The broadcast-NoC shape: four lanes of key partition filter
    (key & 3 == lane) feeding a fused bar tile in last-driven mode."""
    return ScanComposition(
        name="bar-noc-4",
        module_name="dau_mm_bar_noc_job",
        lanes=tuple(
            LaneTile(
                module="dau_int32_bar_aggregation",
                config={"cfg_mode": "2'd0", "cfg_row_count": "64'd0"},
                count_port="bar_count",
                partition=TileInstance(
                    module="dau_int32_pair_key_filter",
                    config={"cfg_key_mask": "32'd3", "cfg_key_match": f"32'd{lane}"},
                ),
            )
            for lane in range(4)
        ),
    )


def _sorted_scan_composition() -> ScanComposition:
    """The range-partitioned shape: a shared range partitioner routing each
    row to one of four filterless sorter lanes."""
    return ScanComposition(
        name="sorted-scan",
        module_name="dau_mm_sorted_scan_job",
        lanes=tuple(LaneTile(module="dau_int32_bitonic_sorter", count_port="sorted_count") for _ in range(4)),
        partitioner=TileInstance(
            module="dau_int32_range_partitioner",
            config={"cfg_splitters": "{32'h0000001E, 32'h00000014, 32'h0000000A}"},
        ),
        sort_capacity=16,  # caller-computed capability data (the sorter's batch row capacity)
    )


def test_bar_noc_top_matches_golden() -> None:
    """Byte-identity golden: the walker's output is pinned so no refactor
    can change a byte of the generated top unnoticed."""
    assert generate_scan_composition_top_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4.v").read_text()


def test_sorted_scan_top_matches_golden() -> None:
    assert generate_scan_composition_top_sv(_sorted_scan_composition()) == (_FIXTURES / "sorted_scan.v").read_text()


def test_capability_words_are_caller_data_and_default_to_unadvertised() -> None:
    """The identity block advertises exactly what the composer computed:
    the bitmaps default to zero (never a static advertisement), the lane
    count is always the composed lane count, and non-default words flow
    into the top parameters and the identity instance."""
    default = generate_scan_composition_top_sv(_bar_noc_composition())
    assert "    parameter [31:0] OPERATOR_BITMAP = 32'h00000000,\n" in default
    assert "    parameter [31:0] LANE_COUNT = 32'd4,\n" in default
    assert "    parameter [31:0] HOST_OPCODE_BITMAP = 32'h00000000,\n" in default
    assert "    parameter [31:0] SORT_CAPACITY = 32'd0\n" in default

    composed = generate_scan_composition_top_sv(
        _bar_noc_composition().model_copy(update={"operator_bitmap": 0x1E, "host_opcode_bitmap": 0x20, "sort_capacity": 16})
    )
    assert "    parameter [31:0] OPERATOR_BITMAP = 32'h0000001E,\n" in composed
    assert "    parameter [31:0] HOST_OPCODE_BITMAP = 32'h00000020,\n" in composed
    assert "    parameter [31:0] SORT_CAPACITY = 32'd16\n" in composed
    for parameter in ("OPERATOR_BITMAP", "LANE_COUNT", "HOST_OPCODE_BITMAP", "SORT_CAPACITY"):
        assert f"        .{parameter}({parameter}),\n" in composed or f"        .{parameter}({parameter})\n" in composed


def test_generated_by_names_the_banner_only() -> None:
    """``generated_by`` swaps the generator name in the banner and changes
    nothing else — callers re-hosting the walker keep byte-identity."""
    default = generate_scan_composition_top_sv(_bar_noc_composition())
    renamed = generate_scan_composition_top_sv(_bar_noc_composition(), generated_by="other.walker")
    differing = [(a, b) for a, b in zip(default.splitlines(), renamed.splitlines()) if a != b]
    assert differing == [
        (
            "// GENERATED by dau_build.scan_composition.generate_scan_composition_top_sv — do not",
            "// GENERATED by other.walker — do not",
        )
    ]


def test_bar_noc_sim_matches_golden() -> None:
    """Byte-identity golden for the sim harness walked from the same
    composition data as the shell top."""
    assert generate_scan_composition_sim_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4_sim.v").read_text()


def test_sorted_scan_sim_matches_golden() -> None:
    """The partitioned shape's harness surfaces the splitters as a
    testbench-driven config input instead of a literal binding."""
    composition = _sorted_scan_composition().model_copy(
        update={"partitioner": TileInstance(module="dau_int32_range_partitioner", config={"cfg_splitters": "cfg_splitters"})}
    )
    text = generate_scan_composition_sim_sv(composition, config_inputs={"cfg_splitters": 96})
    assert text == (_FIXTURES / "sorted_scan_sim.v").read_text()
    assert "    input wire [95:0] cfg_splitters,\n" in text
    assert ".cfg_splitters(cfg_splitters)," in text


def test_sim_module_name_defaults_to_shell_name_with_sim_suffix() -> None:
    text = generate_scan_composition_sim_sv(_bar_noc_composition())
    assert "module dau_mm_bar_noc_job_sim (" in text
    renamed = generate_scan_composition_sim_sv(_bar_noc_composition(), module_name="dau_bar_bench")
    assert "module dau_bar_bench (" in renamed


def test_sim_harness_carries_the_job_control_surface() -> None:
    """The bar-noc-sim control surface: length-grid gate, unit_start,
    lane_rst error recovery, first-error-wins, backdoor RAM."""
    text = generate_scan_composition_sim_sv(_bar_noc_composition(), mem_words=4096, read_latency=2)
    assert "wire length_ok = (input_length_bytes != 32'd0) && (input_length_bytes[3:0] == 4'd0);" in text
    assert "wire unit_start = start && length_ok;" in text
    assert "wire lane_rst = rst || pipeline_error_reset;" in text
    assert "pipeline_error_reset <= done && !prev_done && error;" in text
    assert "error_code = 8'hFE;" in text
    assert ".MEM_WORDS(4096)" in text
    assert ".READ_LATENCY(2)" in text
    # no register aperture in the harness: the job surface is direct ports
    assert "s_axi_aclk" not in text
    assert "ADDR_JOB_CONTROL" not in text
    assert "dau_identity_registers" not in text


def test_register_layout_defaults_place_the_lane_block() -> None:
    layout = RegisterLayout()
    assert layout.lane_register(0, layout.lane_output_address_low) == 0x100
    assert layout.lane_register(3, layout.lane_error) == 0x170


def test_register_layout_drives_the_emitted_localparams() -> None:
    composition = _bar_noc_composition().model_copy(update={"registers": RegisterLayout(lane_base=0x200, lane_stride=0x40)})
    text = generate_scan_composition_top_sv(composition)
    assert "localparam [11:0] ADDR_LANE0_OUTPUT_ADDRESS = 12'h200;" in text
    assert "localparam [11:0] ADDR_LANE1_OUTPUT_ADDRESS = 12'h240;" in text


def test_composition_needs_a_lane() -> None:
    # pydantic surfaces model_post_init errors as ValidationError
    with pytest.raises(ValidationError, match="at least one lane"):
        ScanComposition(name="empty", module_name="dau_empty", lanes=())


def test_shared_partitioner_excludes_lane_partitions() -> None:
    with pytest.raises(ValidationError, match="shared partitioner"):
        ScanComposition(
            name="conflict",
            module_name="dau_conflict",
            lanes=(
                LaneTile(
                    module="dau_tile",
                    count_port="row_count",
                    partition=TileInstance(module="dau_filter"),
                ),
            ),
            partitioner=TileInstance(module="dau_partitioner"),
        )


def _chained_composition() -> ScanComposition:
    """A lane with a two-stage mid-lane chain (filter -> map) ahead of the
    terminal tile, plus a chainless lane to pin cross-lane independence."""
    return ScanComposition(
        name="chained",
        module_name="dau_chained_job",
        lanes=(
            LaneTile(
                module="dau_terminal_tile",
                config={"cfg_mode": "2'd0"},
                count_port="row_count",
                partition=TileInstance(module="dau_key_filter", config={"cfg_key_match": "32'd0"}),
                chain=(
                    TileInstance(module="dau_stage_filter", config={"cfg_op": "3'd1"}),
                    TileInstance(module="dau_stage_map", config={"cfg_shift": "5'd15"}),
                ),
            ),
            LaneTile(module="dau_terminal_tile", count_port="row_count"),
        ),
    )


def test_chain_stages_wire_front_to_terminal_in_order() -> None:
    text = generate_scan_composition_top_sv(_chained_composition())
    # stage 0 consumes the lane front, stage 1 consumes stage 0, the
    # terminal tile consumes stage 1
    assert "    dau_stage_filter chain_0_0 (" in text
    assert ".input_valid(filt_out_valid_0)," in text
    assert "    dau_stage_map chain_0_1 (" in text
    assert ".input_valid(chain0_out_valid_0)," in text
    assert ".output_valid(chain1_out_valid_0)," in text
    tile_block = text.split("dau_terminal_tile tile_0 (")[1].split(");")[0]
    assert ".input_valid(chain1_out_valid_0)," in tile_block
    # config bindings land on their stages
    assert ".cfg_op(3'd1)," in text
    assert ".cfg_shift(5'd15)," in text
    # the chainless lane still consumes its front directly
    tile1_block = text.split("dau_terminal_tile tile_1 (")[1].split(");")[0]
    assert ".input_valid(filt_out_valid_1)," in tile1_block
    assert "chain0_out_valid_1" not in text


def test_chain_status_mux_is_upstream_first() -> None:
    text = generate_scan_composition_top_sv(_chained_composition())
    assert "assign unit_status_valid_0 = tile_status_valid_0 || filt_status_valid_0 || chain0_status_valid_0 || chain1_status_valid_0;" in text
    assert (
        "assign unit_status_error_0 = filt_status_valid_0 ? filt_status_error_0 : "
        "chain0_status_valid_0 ? chain0_status_error_0 : "
        "chain1_status_valid_0 ? chain1_status_error_0 : tile_status_error_0;"
    ) in text
    assert "assign filt_status_ready_0 = unit_status_ready_0 && filt_status_valid_0;" in text
    assert "assign chain0_status_ready_0 = unit_status_ready_0 && !filt_status_valid_0 && chain0_status_valid_0;" in text
    assert "assign chain1_status_ready_0 = unit_status_ready_0 && !filt_status_valid_0 && !chain0_status_valid_0 && chain1_status_valid_0;" in text
    assert "assign tile_status_ready_0 = unit_status_ready_0 && !filt_status_valid_0 && !chain0_status_valid_0 && !chain1_status_valid_0;" in text
    # the chainless lane keeps the plain forwarding glue
    assert "assign unit_status_valid_1 = tile_status_valid_1;" in text


def test_filterless_chained_lane_muxes_chain_before_tile() -> None:
    composition = ScanComposition(
        name="chained-filterless",
        module_name="dau_chained_filterless_job",
        lanes=(
            LaneTile(
                module="dau_terminal_tile",
                count_port="row_count",
                chain=(TileInstance(module="dau_stage_filter"),),
            ),
        ),
    )
    text = generate_scan_composition_top_sv(composition)
    assert "assign unit_status_valid_0 = tile_status_valid_0 || chain0_status_valid_0;" in text
    assert "assign chain0_status_ready_0 = unit_status_ready_0 && chain0_status_valid_0;" in text
    assert "assign tile_status_ready_0 = unit_status_ready_0 && !chain0_status_valid_0;" in text


def test_sim_harness_carries_the_same_chain() -> None:
    text = generate_scan_composition_sim_sv(_chained_composition())
    assert "    dau_stage_filter chain_0_0 (" in text
    assert "    dau_stage_map chain_0_1 (" in text
    tile_block = text.split("dau_terminal_tile tile_0 (")[1].split(");")[0]
    assert ".input_valid(chain1_out_valid_0)," in tile_block


def test_param_override_emits_on_the_tile_and_param_less_stays_byte_identical() -> None:
    """A tile carrying params emits a ``#(.KEY_SPACE(N))`` override between
    the module name and instance; a param-less composition emits exactly as
    before (the byte-identity goldens above pin that)."""
    # the exact "module tile_0 (" substring proves there is no #(...) wedged
    # between the module name and the instance name for a param-less tile
    param_free = generate_scan_composition_top_sv(_bar_noc_composition())
    assert "    dau_int32_bar_aggregation tile_0 (" in param_free

    membership = ScanComposition(
        name="membership",
        module_name="dau_mm_membership_job",
        lanes=(
            LaneTile(
                module="dau_int32_field_sum_aggregation",
                config={"cfg_field_mask": "4'b0010"},
                count_port="aggregated_count",
                chain=(TileInstance(module="dau_int32_key_membership_filter", params={"KEY_SPACE": 6_000_000}),),
            ),
        ),
    )
    text = generate_scan_composition_top_sv(membership)
    assert "    dau_int32_key_membership_filter #(\n        .KEY_SPACE(6000000)\n    ) chain_0_0 (" in text
    # the param-less terminal tile carries no override
    assert "    dau_int32_field_sum_aggregation tile_0 (" in text


def test_param_override_emits_on_partition_and_terminal_tile_slots() -> None:
    composition = ScanComposition(
        name="param-slots",
        module_name="dau_mm_param_slots_job",
        lanes=(
            LaneTile(
                module="dau_terminal_tile",
                count_port="row_count",
                params={"KEY_SPACE": 2048},
                partition=TileInstance(module="dau_key_filter", params={"KEY_SPACE": 128}),
            ),
        ),
    )
    text = generate_scan_composition_top_sv(composition)
    assert "    dau_key_filter #(\n        .KEY_SPACE(128)\n    ) partition_0 (" in text
    assert "    dau_terminal_tile #(\n        .KEY_SPACE(2048)\n    ) tile_0 (" in text


def test_param_override_emits_on_the_shared_partitioner() -> None:
    # a param-less shared partitioner emits only the derived NUM_PARTITIONS (byte-identical)
    plain = generate_scan_composition_top_sv(_sorted_scan_composition())
    assert "    dau_int32_range_partitioner #(\n        .NUM_PARTITIONS(4)\n    ) partitioner (" in plain
    # custom params append after NUM_PARTITIONS
    with_params = _sorted_scan_composition().model_copy(
        update={"partitioner": TileInstance(module="dau_int32_range_partitioner", config={"cfg_splitters": "s"}, params={"KEY_SPACE": 4096})}
    )
    text = generate_scan_composition_top_sv(with_params)
    assert "    dau_int32_range_partitioner #(\n        .NUM_PARTITIONS(4),\n        .KEY_SPACE(4096)\n    ) partitioner (" in text


def test_shared_partitioner_rejects_a_num_partitions_param_override() -> None:
    composition = _sorted_scan_composition().model_copy(
        update={"partitioner": TileInstance(module="dau_int32_range_partitioner", config={"cfg_splitters": "s"}, params={"NUM_PARTITIONS": 8})}
    )
    with pytest.raises(ScanCompositionError, match="NUM_PARTITIONS is derived"):
        generate_scan_composition_top_sv(composition)


def test_param_less_goldens_are_untouched_by_the_param_channel() -> None:
    """The param channel adds a field that defaults empty: every existing
    golden must still match byte-for-byte (this repeats the golden asserts to
    pin them against the param-channel change explicitly)."""
    assert generate_scan_composition_top_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4.v").read_text()
    assert generate_scan_composition_top_sv(_sorted_scan_composition()) == (_FIXTURES / "sorted_scan.v").read_text()
    assert generate_scan_composition_sim_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4_sim.v").read_text()


_FRONT_UNPACK_CONFIG = {
    "cfg_field0_offset": "6'd0",
    "cfg_field0_width": "6'd32",
    "cfg_field0_signed": "1'b0",
    "cfg_field1_offset": "6'd32",
    "cfg_field1_width": "6'd27",
    "cfg_field1_signed": "1'b0",
    "cfg_field2_offset": "6'd0",
    "cfg_field2_width": "6'd1",
    "cfg_field2_signed": "1'b0",
    "cfg_field3_offset": "6'd0",
    "cfg_field3_width": "6'd1",
    "cfg_field3_signed": "1'b0",
    "cfg_bypass": "1'b0",
}


def _front_unpacked_composition() -> ScanComposition:
    """The bar-noc shape with a packed-row front unpacker between the burst
    reader and the broadcast fan-out."""
    return _bar_noc_composition().model_copy(update={"front_unpack": TileInstance(module="dau_int32_row_unpack", config=dict(_FRONT_UNPACK_CONFIG))})


def test_front_unpack_wires_reader_through_unpacker_to_the_fanout() -> None:
    text = generate_scan_composition_top_sv(_front_unpacked_composition())
    # the reader is unchanged: it still drives the scan_* stream
    assert ".stream_valid(scan_valid)," in text
    # the unpacker consumes the reader's scan_* stream ...
    unpack_block = text.split("dau_int32_row_unpack front_unpack (")[1].split(");")[0]
    assert ".input_valid(scan_valid)," in unpack_block
    assert ".input_ready(scan_ready)," in unpack_block
    assert ".input_data(scan_data)," in unpack_block
    assert ".input_last(scan_last)," in unpack_block
    # ... and emits the widened feed_* stream
    assert ".output_valid(feed_valid)," in unpack_block
    assert ".output_ready(feed_ready)," in unpack_block
    assert ".output_data(feed_data)," in unpack_block
    assert ".output_last(feed_last)," in unpack_block
    # its config carries the four field descriptors + cfg_bypass
    assert ".cfg_field1_offset(6'd32)," in unpack_block
    assert ".cfg_bypass(1'b0)," in unpack_block
    # the broadcast fan-out now consumes the unpacker's output, not the reader's
    bcast_block = text.split("dau_stream_broadcast #(")[1].split(");")[0]
    assert ".input_valid(feed_valid)," in bcast_block
    assert ".input_ready(feed_ready)," in bcast_block
    assert ".input_data(feed_data)," in bcast_block
    assert ".input_last(feed_last)," in bcast_block
    # the unpacker sits between the reader and the fan-out in the emission
    assert text.index("dau_axi_burst_reader") < text.index("dau_int32_row_unpack front_unpack (") < text.index("dau_stream_broadcast #(")
    # the feed_* stream wires are declared
    assert "    wire feed_valid;\n    wire feed_ready;\n    wire [63:0] feed_data;\n    wire feed_last;\n" in text


def _wide_front_composition() -> ScanComposition:
    """The rows/cycle-axis shape: a 128-bit front unpacker (OUT_WIDTH=128, one
    whole quad row per beat) feeding a key-mask dispatcher (IN_WIDTH=128) that
    routes each row to one of four filterless lanes."""
    return ScanComposition(
        name="bar-noc-wide",
        module_name="dau_mm_bar_noc_wide_job",
        lanes=tuple(
            LaneTile(module="dau_int32_bar_aggregation", config={"cfg_mode": "2'd0", "cfg_row_count": "64'd0"}, count_port="bar_count")
            for _ in range(4)
        ),
        partitioner=TileInstance(module="dau_int32_key_mask_dispatcher", params={"IN_WIDTH": 128}),
        front_unpack=TileInstance(module="dau_int32_row_unpack", config=dict(_FRONT_UNPACK_CONFIG), params={"OUT_WIDTH": 128}),
    )


def test_wide_front_widens_the_feed_and_threads_the_width_params() -> None:
    # the feed stream is declared at the front unpacker's OUT_WIDTH and both
    # width params land on their instances via the module-parameter channel
    text = generate_scan_composition_top_sv(_wide_front_composition())
    assert "    wire feed_valid;\n    wire feed_ready;\n    wire [127:0] feed_data;\n    wire feed_last;\n" in text
    assert "dau_int32_row_unpack #(\n        .OUT_WIDTH(128)\n    )" in text
    dispatcher_block = text.split("dau_int32_key_mask_dispatcher #(")[1].split(");")[0]
    assert ".NUM_PARTITIONS(4)" in dispatcher_block
    assert ".IN_WIDTH(128)" in dispatcher_block
    assert ".input_data(feed_data)," in dispatcher_block
    # per-lane taps stay the 64-bit two-beat framing (no operator widens)
    assert "assign filt_out_data_0 = part_out_data[63:0];" in text
    # the sim harness mirrors the same width
    sim = generate_scan_composition_sim_sv(_wide_front_composition())
    assert "wire [127:0] feed_data;" in sim


def test_wide_front_requires_a_matching_wide_fanout() -> None:
    # broadcast is 64-bit only: a wide front with no shared partitioner is
    # rejected, as is any feed/fan-out width mismatch (either direction).
    # Constructed directly — model_copy skips model_post_init validation.
    wide_unpack = TileInstance(module="dau_int32_row_unpack", config=dict(_FRONT_UNPACK_CONFIG), params={"OUT_WIDTH": 128})
    plain_lanes = tuple(
        LaneTile(module="dau_int32_bar_aggregation", config={"cfg_mode": "2'd0", "cfg_row_count": "64'd0"}, count_port="bar_count") for _ in range(4)
    )
    with pytest.raises(ValidationError, match="needs a shared partitioner"):
        ScanComposition(name="bad", module_name="dau_bad", lanes=plain_lanes, front_unpack=wide_unpack)
    with pytest.raises(ValidationError, match="widths must agree"):
        ScanComposition(
            name="bad",
            module_name="dau_bad",
            lanes=plain_lanes,
            partitioner=TileInstance(module="dau_int32_key_mask_dispatcher"),
            front_unpack=wide_unpack,
        )
    with pytest.raises(ValidationError, match="feed stream is 64-bit"):
        ScanComposition(
            name="bad",
            module_name="dau_bad",
            lanes=plain_lanes,
            partitioner=TileInstance(module="dau_int32_key_mask_dispatcher", params={"IN_WIDTH": 128}),
        )
    with pytest.raises(ValidationError, match="OUT_WIDTH must be 64 or 128"):
        ScanComposition(
            name="bad",
            module_name="dau_bad",
            lanes=plain_lanes,
            partitioner=TileInstance(module="dau_int32_key_mask_dispatcher", params={"IN_WIDTH": 128}),
            front_unpack=TileInstance(module="dau_int32_row_unpack", config=dict(_FRONT_UNPACK_CONFIG), params={"OUT_WIDTH": 96}),
        )


def test_front_unpack_status_is_latched_and_folded_into_job_error() -> None:
    text = generate_scan_composition_top_sv(_front_unpacked_composition())
    # the front-stage status close-out is consumed (ready tied high) ...
    assert "assign front_unpack_status_ready = 1'b1;" in text
    # ... latched sticky (the close-out is a one-cycle pulse) ...
    assert "    reg front_unpack_error;\n    reg [7:0] front_unpack_error_code;\n" in text
    assert (
        "            if (front_unpack_status_valid && front_unpack_status_error) begin\n"
        "                front_unpack_error <= 1'b1;\n"
        "                front_unpack_error_code <= front_unpack_status_error_code;\n"
        "            end\n"
    ) in text
    # cleared ONLY at peripheral reset, never on job start: a torn/bad-config feed
    # hangs the lane writers (no last arrives) and they recover only on reset, so the
    # latched error must persist until reset (regression: no job-start clear)
    assert "                front_unpack_error <= 1'b0;\n" not in text  # no 16-space job-start clear
    assert "            front_unpack_error <= 1'b0;\n" in text  # the 12-space reset clear remains
    # ... and surfaced into the job error mux after the reader, before the
    # lane writers (first-error-wins), reading the sticky reg
    assert (
        "            if (reader_error) begin\n"
        "                job_error = 1'b1;\n"
        "                job_error_code = reader_error_code;\n"
        "            end else if (front_unpack_error) begin\n"
        "                job_error = 1'b1;\n"
        "                job_error_code = front_unpack_error_code;\n"
        "            end else if (writer_error_0) begin\n"
    ) in text


def test_front_unpack_relaxes_the_length_grid_to_eight_bytes() -> None:
    # packed rows are one 8-byte word each, so a front-unpack composition
    # accepts an 8-byte length grid (an odd packed-row count would round to a
    # non-16-multiple length and be rejected on the 16-byte quad grid)
    packed = generate_scan_composition_top_sv(_front_unpacked_composition())
    assert "wire length_ok = (input_length_bytes != 32'd0) && (input_length_bytes[2:0] == 3'd0);" in packed
    assert ".LENGTH_ALIGN_BITS(3)" in packed
    assert "// the 8-byte row grid is enforced" in packed
    # the sim harness matches
    packed_sim = generate_scan_composition_sim_sv(_front_unpacked_composition())
    assert "wire length_ok = (input_length_bytes != 32'd0) && (input_length_bytes[2:0] == 3'd0);" in packed_sim
    assert ".LENGTH_ALIGN_BITS(3)" in packed_sim
    # a front-unpack-less composition keeps the 16-byte quad grid
    plain = generate_scan_composition_top_sv(_bar_noc_composition())
    assert "wire length_ok = (input_length_bytes != 32'd0) && (input_length_bytes[3:0] == 4'd0);" in plain
    assert ".LENGTH_ALIGN_BITS(4)" in plain
    assert "// the 16-byte row grid is enforced" in plain


def test_front_unpack_with_a_shared_partitioner_feeds_the_partitioner() -> None:
    composition = _sorted_scan_composition().model_copy(
        update={"front_unpack": TileInstance(module="dau_int32_row_unpack", config=dict(_FRONT_UNPACK_CONFIG))}
    )
    text = generate_scan_composition_top_sv(composition)
    part_block = text.split(") partitioner (")[1].split(");")[0]
    assert ".input_valid(feed_valid)," in part_block
    assert ".input_last(feed_last)," in part_block
    assert text.index("dau_int32_row_unpack front_unpack (") < text.index(") partitioner (")


def test_front_unpack_sim_harness_carries_the_unpacker() -> None:
    text = generate_scan_composition_sim_sv(_front_unpacked_composition())
    unpack_block = text.split("dau_int32_row_unpack front_unpack (")[1].split(");")[0]
    assert ".input_valid(scan_valid)," in unpack_block
    assert ".output_valid(feed_valid)," in unpack_block
    bcast_block = text.split("dau_stream_broadcast #(")[1].split(");")[0]
    assert ".input_valid(feed_valid)," in bcast_block
    assert "assign front_unpack_status_ready = 1'b1;" in text


def test_front_unpack_absent_stays_byte_identical() -> None:
    """The front-unpack slot defaults to ``None``; every existing golden must
    still match byte-for-byte (the additive change never touches the
    front-unpack-less emission)."""
    assert generate_scan_composition_top_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4.v").read_text()
    assert generate_scan_composition_top_sv(_sorted_scan_composition()) == (_FIXTURES / "sorted_scan.v").read_text()
    assert generate_scan_composition_sim_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4_sim.v").read_text()


_CONFORMING_TILE = """
module lane_tile (
    input  wire logic        clk,
    input  wire logic        rst,
    input  wire logic [31:0] cfg_thing,
    input  wire logic        input_valid,
    output logic             input_ready,
    input  wire logic [63:0] input_data,
    input  wire logic        input_last,
    output logic             output_valid,
    input  wire logic        output_ready,
    output logic [63:0]      output_data,
    output logic             output_last,
    output logic             status_valid,
    input  wire logic        status_ready,
    output logic             status_error,
    output logic [7:0]       status_error_code,
    output logic [63:0]      row_count
);
endmodule
"""


def _lane_tile_composition(config: dict[str, str]) -> ScanComposition:
    return ScanComposition(
        name="introspected",
        module_name="dau_introspected_job",
        lanes=(LaneTile(module="lane_tile", config=config, count_port="row_count"),),
    )


def test_sources_arm_interface_validation(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    text = generate_scan_composition_top_sv(_lane_tile_composition({"cfg_thing": "32'd7"}), sources=(source,))
    assert "lane_tile tile_0 (" in text
    assert ".cfg_thing(32'd7)," in text


def test_sources_reject_a_config_binding_typo(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    with pytest.raises(ScanCompositionError, match=r"config binding 'cfg_thingz' is not an input port \(cfg ports: cfg_thing\)"):
        generate_scan_composition_top_sv(_lane_tile_composition({"cfg_thingz": "32'd7"}), sources=(source,))


def test_sources_reject_a_missing_module(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    composition = _lane_tile_composition({}).model_copy(update={"partitioner": TileInstance(module="dau_absent_partitioner")})
    with pytest.raises(ScanCompositionError, match="dau_absent_partitioner.*not found"):
        generate_scan_composition_top_sv(composition, sources=(source,))


def test_sim_generator_arms_the_same_interface_validation(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    text = generate_scan_composition_sim_sv(_lane_tile_composition({"cfg_thing": "32'd7"}), sources=(source,))
    assert "lane_tile tile_0 (" in text
    with pytest.raises(ScanCompositionError, match=r"config binding 'cfg_thingz' is not an input port"):
        generate_scan_composition_sim_sv(_lane_tile_composition({"cfg_thingz": "32'd7"}), sources=(source,))


def test_sources_validate_chain_stages(tmp_path: Path) -> None:
    """Chain stages arm the same slang interface validation as terminal
    tiles (contract conformance, config-binding names) but need no count
    port."""
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    chained = _lane_tile_composition({}).model_copy(
        update={
            "lanes": (LaneTile(module="lane_tile", count_port="row_count", chain=(TileInstance(module="lane_tile", config={"cfg_thing": "32'd1"}),)),)
        }
    )
    text = generate_scan_composition_top_sv(chained, sources=(source,))
    assert "lane_tile chain_0_0 (" in text

    with pytest.raises(ScanCompositionError, match=r"config binding 'cfg_typo' is not an input port"):
        generate_scan_composition_top_sv(
            chained.model_copy(
                update={
                    "lanes": (
                        LaneTile(module="lane_tile", count_port="row_count", chain=(TileInstance(module="lane_tile", config={"cfg_typo": "32'd1"}),)),
                    )
                }
            ),
            sources=(source,),
        )

    with pytest.raises(ScanCompositionError, match="dau_absent_stage.*not found"):
        generate_scan_composition_top_sv(
            chained.model_copy(
                update={"lanes": (LaneTile(module="lane_tile", count_port="row_count", chain=(TileInstance(module="dau_absent_stage"),)),)}
            ),
            sources=(source,),
        )


def test_sources_reject_a_missing_count_port(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    composition = _lane_tile_composition({}).model_copy(update={"lanes": (LaneTile(module="lane_tile", count_port="bar_count"),)})
    with pytest.raises(ScanCompositionError, match="missing declared count port 'bar_count'"):
        generate_scan_composition_top_sv(composition, sources=(source,))


def test_sources_validate_the_front_unpacker(tmp_path: Path) -> None:
    """The front unpacker arms the same slang interface validation as the
    other stream tiles (contract conformance, config-binding names) but,
    like a partition filter, needs no count port."""
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    composition = _lane_tile_composition({}).model_copy(update={"front_unpack": TileInstance(module="lane_tile", config={"cfg_thing": "32'd1"})})
    text = generate_scan_composition_top_sv(composition, sources=(source,))
    assert "lane_tile front_unpack (" in text

    with pytest.raises(ScanCompositionError, match=r"config binding 'cfg_typo' is not an input port"):
        generate_scan_composition_top_sv(
            composition.model_copy(update={"front_unpack": TileInstance(module="lane_tile", config={"cfg_typo": "32'd1"})}), sources=(source,)
        )
    with pytest.raises(ScanCompositionError, match="dau_absent_unpacker.*not found"):
        generate_scan_composition_top_sv(
            composition.model_copy(update={"front_unpack": TileInstance(module="dau_absent_unpacker")}), sources=(source,)
        )
