from __future__ import annotations

from pathlib import Path

import pytest
from pydantic import ValidationError

from dau_build.scan_composition import LaneTile, RegisterLayout, ScanComposition, ScanCompositionError, TileInstance, generate_scan_composition_top_sv

_FIXTURES = Path(__file__).parent / "fixtures" / "scan_composition"


def _bar_noc_composition() -> ScanComposition:
    """The broadcast-NoC shape: four lanes of key partition filter
    (key & 3 == lane) feeding a fused bar tile in last-driven mode."""
    return ScanComposition(
        name="bar-noc-4",
        module_name="dau_mm_bar_noc_job",
        lanes=tuple(
            LaneTile(
                module="dau_int32_bar_aggregation",
                config={"cfg_mode": "2'd0", "cfg_row_count": "64'd0"},
                count_port="bar_count",
                partition=TileInstance(
                    module="dau_int32_pair_key_filter",
                    config={"cfg_key_mask": "32'd3", "cfg_key_match": f"32'd{lane}"},
                ),
            )
            for lane in range(4)
        ),
    )


def _sorted_scan_composition() -> ScanComposition:
    """The range-partitioned shape: a shared range partitioner routing each
    row to one of four filterless sorter lanes."""
    return ScanComposition(
        name="sorted-scan",
        module_name="dau_mm_sorted_scan_job",
        lanes=tuple(LaneTile(module="dau_int32_bitonic_sorter", count_port="sorted_count") for _ in range(4)),
        partitioner=TileInstance(
            module="dau_int32_range_partitioner",
            config={"cfg_splitters": "{32'h0000001E, 32'h00000014, 32'h0000000A}"},
        ),
    )


def test_bar_noc_top_matches_golden() -> None:
    """Byte-identity golden: the walker's output is pinned so no refactor
    can change a byte of the generated top unnoticed."""
    assert generate_scan_composition_top_sv(_bar_noc_composition()) == (_FIXTURES / "bar_noc_4.v").read_text()


def test_sorted_scan_top_matches_golden() -> None:
    assert generate_scan_composition_top_sv(_sorted_scan_composition()) == (_FIXTURES / "sorted_scan.v").read_text()


def test_generated_by_names_the_banner_only() -> None:
    """``generated_by`` swaps the generator name in the banner and changes
    nothing else — callers re-hosting the walker keep byte-identity."""
    default = generate_scan_composition_top_sv(_bar_noc_composition())
    renamed = generate_scan_composition_top_sv(_bar_noc_composition(), generated_by="other.walker")
    differing = [(a, b) for a, b in zip(default.splitlines(), renamed.splitlines()) if a != b]
    assert differing == [
        (
            "// GENERATED by dau_build.scan_composition.generate_scan_composition_top_sv — do not",
            "// GENERATED by other.walker — do not",
        )
    ]


def test_register_layout_defaults_place_the_lane_block() -> None:
    layout = RegisterLayout()
    assert layout.lane_register(0, layout.lane_output_address_low) == 0x100
    assert layout.lane_register(3, layout.lane_error) == 0x170


def test_register_layout_drives_the_emitted_localparams() -> None:
    composition = _bar_noc_composition().model_copy(update={"registers": RegisterLayout(lane_base=0x200, lane_stride=0x40)})
    text = generate_scan_composition_top_sv(composition)
    assert "localparam [11:0] ADDR_LANE0_OUTPUT_ADDRESS = 12'h200;" in text
    assert "localparam [11:0] ADDR_LANE1_OUTPUT_ADDRESS = 12'h240;" in text


def test_composition_needs_a_lane() -> None:
    # pydantic surfaces model_post_init errors as ValidationError
    with pytest.raises(ValidationError, match="at least one lane"):
        ScanComposition(name="empty", module_name="dau_empty", lanes=())


def test_shared_partitioner_excludes_lane_partitions() -> None:
    with pytest.raises(ValidationError, match="shared partitioner"):
        ScanComposition(
            name="conflict",
            module_name="dau_conflict",
            lanes=(
                LaneTile(
                    module="dau_tile",
                    count_port="row_count",
                    partition=TileInstance(module="dau_filter"),
                ),
            ),
            partitioner=TileInstance(module="dau_partitioner"),
        )


_CONFORMING_TILE = """
module lane_tile (
    input  wire logic        clk,
    input  wire logic        rst,
    input  wire logic [31:0] cfg_thing,
    input  wire logic        input_valid,
    output logic             input_ready,
    input  wire logic [63:0] input_data,
    input  wire logic        input_last,
    output logic             output_valid,
    input  wire logic        output_ready,
    output logic [63:0]      output_data,
    output logic             output_last,
    output logic             status_valid,
    input  wire logic        status_ready,
    output logic             status_error,
    output logic [7:0]       status_error_code,
    output logic [63:0]      row_count
);
endmodule
"""


def _lane_tile_composition(config: dict[str, str]) -> ScanComposition:
    return ScanComposition(
        name="introspected",
        module_name="dau_introspected_job",
        lanes=(LaneTile(module="lane_tile", config=config, count_port="row_count"),),
    )


def test_sources_arm_interface_validation(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    text = generate_scan_composition_top_sv(_lane_tile_composition({"cfg_thing": "32'd7"}), sources=(source,))
    assert "lane_tile tile_0 (" in text
    assert ".cfg_thing(32'd7)," in text


def test_sources_reject_a_config_binding_typo(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    with pytest.raises(ScanCompositionError, match=r"config binding 'cfg_thingz' is not an input port \(cfg ports: cfg_thing\)"):
        generate_scan_composition_top_sv(_lane_tile_composition({"cfg_thingz": "32'd7"}), sources=(source,))


def test_sources_reject_a_missing_module(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    composition = _lane_tile_composition({}).model_copy(update={"partitioner": TileInstance(module="dau_absent_partitioner")})
    with pytest.raises(ScanCompositionError, match="dau_absent_partitioner.*not found"):
        generate_scan_composition_top_sv(composition, sources=(source,))


def test_sources_reject_a_missing_count_port(tmp_path: Path) -> None:
    source = tmp_path / "lane_tile.sv"
    source.write_text(_CONFORMING_TILE)
    composition = _lane_tile_composition({}).model_copy(update={"lanes": (LaneTile(module="lane_tile", count_port="bar_count"),)})
    with pytest.raises(ScanCompositionError, match="missing declared count port 'bar_count'"):
        generate_scan_composition_top_sv(composition, sources=(source,))
